---

###########################################################################################
# This file calls the OS specific tasks to configure HANA specific clustering resources  #8
###########################################################################################
- name:                                "HANA Pacemaker: - HSR Create helper variables"
  ansible.builtin.set_fact:
    DB:                                "{{ db_sid | upper }}/HDB{{ db_instance_number }}"

# Clustering commands are based on the Host OS
- name: "5.8 HANADB Pacemaker - configure pre-requisites"
  ansible.builtin.include_tasks:  "5.8.4.0-clusterPrep-ScaleOut-{{ ansible_os_family }}.yml"
  apply:
    vars:
      ansible_python_interpreter:  python3
    environment:
      HOME:                      "/usr/sap/{{ db_sid | upper }}/home"
      PYTHONHOME:                "/usr/sap/{{ DB }}/exe/Python3"
      DIR_EXECUTABLE:            "/usr/sap/{{ DB }}/exe"
      SAP_RETRIEVAL_PATH:        "/usr/sap/{{ DB }}/{{ virtual_host }}"
      DIR_SYSEXE:                "/usr/sap/{{ db_sid | upper }}/SYS/exe/hdb"
      SAPSYSTEMNAME:             "{{ db_sid | upper }}"
      SECUDIR:                   "/usr/sap/{{ DB }}/{{ virtual_host }}/sec"
      DAT_BIN_DIR:               "/usr/sap/{{ DB }}/exe/dat_bin_dir"
      DIR_INSTANCE:              "/usr/sap/{{ DB }}"
      PYTHONPATH:                "/usr/sap/{{ DB }}/exe/Py3:/usr/sap/HDB/SYS/global/hdb/custom/python_support:/usr/sap/{{ DB }}/exe/python_support:/usr/sap/{{ DB }}/{{ virtual_host }}:/usr/sap/{{ DB }}/exe:/usr/sap/{{ DB }}/exe/testscripts:/usr/sap/{{ DB }}/exe/Python3/lib/python3.7"
      PATH:                      "/usr/sap/{{ DB }}/exe/krb5/bin:/usr/sap/{{ DB }}/exe/krb5/sbin:/usr/sap/{{ DB }}/{{ virtual_host }}:/usr/sap/{{ DB }}:/usr/sap/{{ DB }}/exe:/usr/sap/{{ DB }}/exe/mdc:/usr/sap/{{ DB }}/exe/Python3/bin:/usr/sap/{{ DB }}/exe/dat_bin_dir:/usr/sap/HDB/home:/usr/sap/HDB/home/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib/mit/bin"
      LD_LIBRARY_PATH:           "/usr/sap/{{ DB }}/exe/krb5/lib/krb5/plugins/preauth:/usr/sap/{{ DB }}/exe/krb5/lib:/usr/sap/{{ DB }}/exe:/usr/sap/{{ DB }}/exe/Python3/lib:/usr/sap/{{ DB }}/exe/Py3:/usr/sap/{{ DB }}/exe/filter:/usr/sap/{{ DB }}/exe/dat_bin_dir:/usr/sap/{{ DB }}/exe/plugins/afl:/usr/sap/{{ DB }}/exe/plugins/lcapps:/usr/sap/{{ DB }}/exe/plugins/repository:/usr/sap/{{ DB }}/exe/plugins/epmmds:/usr/sap/HDB/SYS/global/hdb/federation:/usr/sap/HDB/SYS/global/hdb/plugins/3rd_party_libs:/usr/sap/HDB/SYS/global/hdb/plugins/1st_party_libs"

- name: "5.8 HANADB Pacemaker - import - SAP HanaSRMultiTarget"
  ansible.builtin.include_tasks:   5.8.3-SAPHanaSRMultiTarget.yml

- name: "5.8 HANADB Pacemaker - configure cluster resources"
  ansible.builtin.include_tasks:   "5.8.4.1-cluster-ScaleOut-{{ ansible_os_family }}.yml"
...
