# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
- name:                                "5.8. HANA Database Pacemaker - Scale-out - Set facts"
  ansible.builtin.import_tasks:        5.8.1-set_runtime_facts.yml

- name:                                "5.8 HANA DB Pacemaker - import - pre_checks"
  ansible.builtin.import_tasks:        5.8.2-pre_checks.yml

- name:                                "5.8. HANA Database Pacemaker - Scale-out - Setup HANA System Replication MultiTarget"
  ansible.builtin.include_tasks:       5.8.3-SAPHanaSRMultiTarget-{{ ansible_os_family }}.yml
  when:
    - node_tier in ['hana','observer']

# Scale-Out HSR Specific provision task with its own unique sequence
- name:                                "5.8. HANA Database Pacemaker - Scale-out - Provision Scale-out HANA System Replication"
  ansible.builtin.import_tasks:        5.8.4-provision-ScaleOut.yml
  when:
    - not hana_cluster_existence_check

- name:                                "5.8. HANA Database Pacemaker - Scale-out - Post Provision Report"
  ansible.builtin.import_tasks:        5.8.5-post_provision_report.yml
