---
- name:                                "5.8 HANADB Pacemaker - import - set_runtime_facts"
  ansible.builtin.import_tasks:        5.8.1-set_runtime_facts.yml

- name:                                "5.8 HANADB Pacemaker - import - pre_checks"
  ansible.builtin.import_tasks:        5.8.2-pre_checks.yml

- name:                                "5.8 HANADB Pacemaker - import - SAP HanaSR"
  ansible.builtin.include_tasks:       5.8.3-SAPHanaSRMultiTarget-{{ ansible_os_family }}.yml
  when:
    - node_tier in ['hana','observer']

# Scale-Out HSR Specific provision task with its own unique sequence
- name:                                "5.8 HANADB Pacemaker - import - provision Scale-Out-HSR"
  ansible.builtin.import_tasks:        5.8.4-provision-ScaleOut.yml
  when:
    - not hana_cluster_existence_check

- name:                                "5.8 HANADB Pacemaker - import - post_provision_report"
  ansible.builtin.import_tasks:        5.8.5-post_provision_report.yml
