---

# sapcontrol EXITCODES

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     0  Last web method call successful
# |     1  Last web method call failed, invalid parameter
# |     2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait
# |        timed out
# |        CheckSystemCertificates detected warnings
# |     3  GetProcessList succeeded, all processes running correctly
# |        CheckSystemCertificates detected errors
# |     4  GetProcessList succeeded, all processes stopped
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Determine if HANA is running
  become_user:                         "{{ db_sid | lower }}adm"
  become:                              true
  ansible.builtin.command:             "{{ sapcontrol_command }} -function GetProcessList"
  vars:
    ansible_python_interpreter:        python3
  failed_when:                         false
  changed_when:                        false
  register:                            hana_running

- name:                                Ensure HANA is running
  become_user:                         "{{ db_sid | lower }}adm"
  ansible.builtin.command:             "{{ sapcontrol_command }} -function StartWait {{ hana_stop_start_timeout_in_seconds }} {{ hana_stop_start_delay_in_seconds }}"
  when:                                hana_running.rc != 3

- name:                                Check if HANA is running
  become_user:                         "{{ db_sid | lower }}adm"
  ansible.builtin.command:             "{{ sapcontrol_command }} -function GetProcessList"
  changed_when:                        false
  register:                            hana_running
  failed_when:                         hana_running.rc != 3

...

