# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# sapcontrol EXITCODES

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     0  Last web method call successful
# |     1  Last web method call failed, invalid parameter
# |     2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait
# |        timed out
# |        CheckSystemCertificates detected warnings
# |     3  GetProcessList succeeded, all processes running correctly
# |        CheckSystemCertificates detected errors
# |     4  GetProcessList succeeded, all processes stopped
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                "04.01 Start HANA"
  block:

    - name:                            "04.01 Start HANA - Determine if HANA is running on {{ ansible_hostname }}"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function GetProcessList"
      changed_when:                    false
      failed_when:                     false
      register:                        is_hana_running
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        HOME:                          /usr/sap/{{ db_sid | upper }}/home
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        PATH:                          /usr/bin:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

    - name:                            "04.01 Start HANA - Determine if HANA is running on {{ ansible_hostname }}"
      ansible.builtin.debug:
        var:                           is_hana_running
        verbosity:                     2

    - name:                            "04.01 Start HANA - Ensure HANA is running on {{ ansible_hostname }}"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function StartWait {{ hana_stop_start_timeout_in_seconds }} {{ hana_stop_start_delay_in_seconds }}"
      when:                            is_hana_running.rc != 3
      changed_when:                    false
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        HOME:                          /usr/sap/{{ db_sid | upper }}/home
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        PATH:                          /usr/bin:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

    - name:                            "04.01 Start HANA - Validate HANA is running  on {{ ansible_hostname }}"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                              true
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function GetProcessList"
      changed_when:                    false
      register:                        hana_running
      failed_when:                     hana_running.rc != 3
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        HOME:                          /usr/sap/{{ db_sid | upper }}/home
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        PATH:                          /usr/bin:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

  rescue:
    - name:                            "04.01 Start HANA - Rescue: Ensure HANA is running on {{ ansible_hostname }}"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell:           "HDB start"
      changed_when:                    false
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        HOME:                          /usr/sap/{{ db_sid | upper }}/home
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        PATH:                          /usr/bin:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

    - name:                            "04.01 Start HANA - Rescue: Validate HANA is running  on {{ ansible_hostname }}"
      become_user:                     "{{ db_sid | lower }}adm"
      become:                          true
      ansible.builtin.shell:           "{{ sapcontrol_command }} -function GetProcessList"
      changed_when:                    false
      register:                        hana_running
      failed_when:                     hana_running.rc != 3
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        HOME:                          /usr/sap/{{ db_sid | upper }}/home
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        PATH:                          /usr/bin:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

...
