# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# | Post processing - TBC - pending for DB2 - the whole playbook needs         |
# | adapting for DB2 resources                                                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "5.7.4 DB2 Pacemaker - Pause to give cluster time to stabilize"
  ansible.builtin.pause:
    seconds:                           "{{ cluster_status_report_wait_in_s }}"

- name:                                "5.7.4 DB2 Pacemaker - Check the post-provisioning cluster status"
  ansible.builtin.command:             "{{ cluster_status_cmd[ansible_os_family] }}"
  register:                            cluster_status_report
  changed_when:                        false
  failed_when:                         false

- name:                                "5.7.4 DB2 Pacemaker - Output cluster status"
  ansible.builtin.debug:
    msg:                               "Cluster status: {{ cluster_status_report.stdout }}"

- name:                                "5.7.4 DB2 Pacemaker - Check the SBD devices status"
  ansible.builtin.shell:               set -o pipefail && crm_mon -1 | grep sbd
  register:                            sbd_status_report
  changed_when:                        false
  failed_when:                         false
  when:                                ansible_os_family | upper == 'SUSE'

- name:                                "5.7.4 DB2 Pacemaker - Output SBD status"
  ansible.builtin.debug:
    msg:                               "SBD status: {{ sbd_status_report.stdout }}"
  when:                                ansible_os_family | upper == 'SUSE'
