# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# sapcontrol EXITCODES

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     Pre checks                                                             |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# Note -  feng shui is required to change db specific naming conventions for these variables. Right now re-using the variables for DB2
# - name:                                "Check the fencing agent configuration variables are set"
#   ansible.builtin.assert:
#     that:
#       - "sap_hana_fencing_spn_subscription_id is defined"
#       - "sap_hana_fencing_spn_subscription_id | trim | length > 0"
#       - "sap_hana_fencing_spn_tenant_id is defined"
#       - "sap_hana_fencing_spn_tenant_id | trim | length > 0"
#       - "sap_hana_fencing_spn_client_id is defined"
#       - "sap_hana_fencing_spn_client_id | trim | length > 0"
#       - "sap_hana_fencing_spn_client_pwd is defined"
#       - "sap_hana_fencing_spn_client_pwd | trim | length > 0"
#     fail_msg:                          "Fencing SPN details are missing"

- name:                                "5.7.2 DB2 Pacemaker - Check the required cluster password is set"
  ansible.builtin.assert:
    that:
      - "password_ha_db_cluster is defined"
      - "password_ha_db_cluster | trim | length > 0"
    fail_msg:                          The cluster password is not defined

- name:                                "5.7.2 DB2 Pacemaker - Check the required Clustering scripts are available"
  ansible.builtin.stat:
    path:                              "/usr/sbin/crm"
  register:                            cluster_scripts_status_results
  failed_when:                         not cluster_scripts_status_results.stat.exists
  when: ansible_os_family == 'Suse'

- name:                                "5.7.2 DB2 Pacemaker - Create run flag directory"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    state:                             directory
    mode:                              0755

- name:                                "5.7.2 DB2 Pacemaker - Reset run flag"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/sap_deployment_db2_pcm.txt
    state:                             absent
  when:                                reinstall

- name:                                "5.7.2 DB2 Pacemaker - Check if deployed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_db2_pcm.txt
  register:                            db2_pacemaker

- name:                                "5.7.2 DB2 Pacemaker - Check if a cluster has already been prepared (save)"
  ansible.builtin.set_fact:
    db2_cluster_existence_check:       "{{ db2_pacemaker.stat.exists }}"

- name:                                "5.7.2 DB2 Pacemaker - Check if a cluster has already been prepared (show)"
  ansible.builtin.debug:
    msg:                               "Cluster check return value: {{ db2_cluster_existence_check }}"
