# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
- name:                                "5.5 HANA Pacemaker - Set runtime facts"
  ansible.builtin.include_tasks:        5.5.1-set_runtime_facts.yml

- name:                                "5.5 HANA Pacemaker - Pre checks"
  ansible.builtin.include_tasks:        5.5.2-pre_checks.yml

- name:                                "5.5 HANA Pacemaker - Configure HANA System Replication"
  ansible.builtin.include_tasks:       5.5.3-SAPHanaSR.yml

- name:                                "5.5 HANA Pacemaker - Cluster Provisioning"
  ansible.builtin.include_tasks:
    file:                              5.5.4-provision.yml
    apply:
      tags:
        - 5.5.4-provision
      become:                          true
      become_user:                     root

- name:                                "5.5 HANA Pacemaker - Post provision report"
  ansible.builtin.include_tasks:        5.5.5-post_provision_report.yml

...
