---
- name: "5.5 HANADB Pacemaker - import - set_runtime_facts"
  ansible.builtin.import_tasks: 5.5.1-set_runtime_facts.yml

- name: "5.5 HANADB Pacemaker - import - pre_checks"
  ansible.builtin.import_tasks: 5.5.2-pre_checks.yml

- name: "5.5 HANADB Pacemaker - import - SAP HanaSR"
  ansible.builtin.import_tasks: 5.5.3-SAPHanaSR.yml
  when: not database_scale_out

- name: "5.5 HANADB Pacemaker - import - SAP HanaSR Scale-out"
  ansible.builtin.import_tasks: 5.5.3.1-SAPHanaSR-Scaleout.yml
  when: database_scale_out

- name: "5.5 HANADB Pacemaker - import - provision"
  ansible.builtin.import_tasks: 5.5.4-provision.yml
  when: not hana_cluster_existence_check

- name: "5.5 HANADB Pacemaker - import - post_provision_report"
  ansible.builtin.import_tasks: 5.5.5-post_provision_report.yml
