# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the HANA Cloud Meansurement Tool                    |
# |                  Setup HCMT                                                |
# |                  change executionplan.json to allow non-interactive runs   |
# |                  reduce repeat value to 1                                  |
# |                  execute hcmt                                              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---

- name:                                "HCMT"
  block:

# +------------------------------------4--------------------------------------*/

    - name: Setup HCMT
      ansible.builtin.command:         ./hcmtsetup
      args:
        chdir:                         "{{ target_media_location }}/hcmt/setup"
        creates:                       "{{ target_media_location }}/hcmt/setup/config"

    - name:                            Set Request to false to allow non-interactive run
      ansible.builtin.replace:
        path:                          "{{ target_media_location }}/hcmt/setup/config/executionplan.json"
        regexp:                        '"Request": "true"'
        replace:                       '"Request": "false"'

    - name:                            Lower Repeat Value to 1 to reduce long runtime
      ansible.builtin.replace:
        path:                          "{{ target_media_location }}/hcmt/setup/config/executionplan.json"
        regexp:                        '"Value": "2"'
        replace:                       '"Value": "1"'

    - name:                            Execute HCMT
      ansible.builtin.command:         ./hcmt -v -p config/executionplan.json
      changed_when:                    false
      args:
        chdir:                         "{{ target_media_location }}/hcmt/setup"

    - name:                            Find HCMT test result file
      ansible.builtin.find:
        paths:                         "{{ target_media_location }}/hcmt/setup"
        patterns:                      "hcmtresult-*.zip"
        recurse:                       false
      register:                        file_2_fetch

    - name:                            Fetch the HCMT result
      ansible.builtin.fetch:
        src:                           "{{ item.path }}"
        dest:                          "{{ _workspace_directory }}/logs"
        flat:                          true
        fail_on_missing:               false
      with_items: "{{ file_2_fetch.files }}"

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
