# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

azure_utility_repo: https://raw.githubusercontent.com/Azure/SAP-on-Azure-Scripts-and-Utilities
powershell_version: 7.3.12

# https://github.com/Azure/SAP-on-Azure-Scripts-and-Utilities/blob/main/QualityCheck/QualityCheck.ps1
vm_operating_system_map:
  SUSE: "SUSE"
  REDHAT: "RedHat"
  ORACLELINUX: "OracleLinux"
  WINDOWS: "Windows"

vm_database_map:
  HANA: HANA
  DB2: Db2
  SYBASE: ASE
  SQLSERVER: MSSQL
  ORACLE: Oracle
  ORACLE-ASM: Oracle

vm_role_map:
  HANA: DB
  DB2: DB
  SYBASE: DB
  SQLSERVER: DB
  ORACLE: DB
  ORACLE-ASM: DB
  SCS: ASCS
  ERS: ASCS
  PAS: APP
  APP: APP

high_availability_agent_map:
  AFA: FencingAgent
  SBD: SBD
  ISCSI: SBD
