---
# SAP Note 2777782 - SAP HANA DB: Recommended OS Settings for RHEL 8
# Generic editor to add or edit GRUB arguments
- name:                                "2.10 sap-notes: - Register GRUB config file content"
  ansible.builtin.set_fact:
    grub_config_file_content:          "{{ lookup('file', grub_config_file) }}"

- name:                                "2.10 sap-notes: - Update the current setting"
  ansible.builtin.lineinfile:
    path:                              "{{ grub_config_file }}"
    regexp:                            '^GRUB_CMDLINE_LINUX="(.*){{ item.key }}=(?:[^\s]+)( .*"|")'
    line:                              'GRUB_CMDLINE_LINUX="\1{{ item.key }}={{ item.value }}\2'
    backrefs:                          true
  when: item.key in grub_config_file_content
  tags: skip_ansible_lint

- name:                                "2.10 sap-notes: - Add the argument if it does not exist"
  ansible.builtin.lineinfile:
    path:                              "{{ grub_config_file }}"
    regexp:                            '^GRUB_CMDLINE_LINUX="(.*)"'
    line:                              'GRUB_CMDLINE_LINUX="\1 {{ item.key }}={{ item.value }}"'
    backrefs:                          true
  when: item.key not in grub_config_file_content

...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
