---
- name:                                "1.17 Generic Pacemaker - Set Runtime Facts"
  ansible.builtin.import_tasks:                        1.17.0-set_runtime_facts.yml

- name:                                "1.17 Generic Pacemaker - Run pre-checks"
  ansible.builtin.import_tasks:                        1.17.1-pre_checks.yml

# Import this task only if the cluster is not yet created
- name:                                "1.17 Generic Pacemaker - Provision"
  block:
    - name:                            "1.17 Generic Pacemaker - Provision Pacemaker"
      ansible.builtin.import_tasks:                    1.17.2-provision.yml
  tags:
    - 1.17.2-provision
  when: not cluster_existence_check == '0'

- name:                                "1.17 Generic Pacemaker - Post provision report"
  ansible.builtin.import_tasks:                        1.17.3-post_provision_report.yml

...
