---
# TODO: Maybe move these to a group_vars/all/distro file so that they
# can be shared by all playbooks/tasks automatically, and extend with
# standardised versions of all similar patterns used in the playbooks.
distro_name:                           "{{ ansible_os_family | upper }}-{{ ansible_distribution_major_version }}"
distribution_id:                       "{{ ansible_distribution | lower ~ ansible_distribution_major_version }}"
distribution_full_id:                  "{{ ansible_distribution | lower ~ ansible_distribution_version }}"
