# /*---------------------------------------------------------------------------8
# |                                                                            |
# |             SAP: Register BOM                                              |
# |         SAP SCS: deploy SCS Parameter file install template                |
# |         SAP SCS: Install                                                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---

- name:                                "User Creation: Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile_template:              "{{ bom_base_name }}-generic-inifile-param.j2"
    sap_inifile:                       "{{ bom_base_name }}-generic-{{ sid_to_be_deployed.sid | lower }}-{{ ansible_hostname }}.params"
    dir_params:                        "{{ tmp_directory }}/.{{ sid_to_be_deployed.sid | lower }}-params"

- name:                                "User Creation: Create directories"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    mode:                              '{{ item.mode }}'
  loop:
    - { mode: '0755', path: '{{ dir_params }}' }
    - { mode: '0755', path: '{{ tmp_directory }}/{{ sid_to_be_deployed.sid | upper }}' }
    - { mode: '0755', path: '/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}' }

- name:                                "User Creation: Set the Server name list"
  ansible.builtin.set_fact:
    scs_server_temp:                   "{{ scs_server_temp | default([]) + [item] }}"
  with_items:
    - "{{ query('inventory_hostnames', '{{ sid_to_be_deployed.sid | upper }}_SCS') }}"
    - "{{ query('inventory_hostnames', '{{ sid_to_be_deployed.sid | upper }}_DB') }}"
    - "{{ query('inventory_hostnames', '{{ sid_to_be_deployed.sid | upper }}_PAS') }}"
    - "{{ query('inventory_hostnames', '{{ sid_to_be_deployed.sid | upper }}_APP') }}"

- name:                                "User Creation: Set the SCS Server name"
  ansible.builtin.set_fact:
    scs_server:                        "{{ scs_server_temp | first }}"

- name:                                "User Creation: reset"
  ansible.builtin.file:
    path:                              "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
    state:                             absent
  when:                                reinstall

- name:                                "User Creation: check if Completed"
  ansible.builtin.stat:
    path:                              "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
  register:                            users_created

- name:                                "User Creation: check if installed"
  ansible.builtin.debug:
    var:                               users_created
    verbosity:                         2

- name:                                "User Creation: Include 3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-register
  vars:
    bom_name:                          "{{ bom_base_name }}"
    task_prefix:                       "GENERIC: "
    always_upload_jinja_templates:     false

- name:                                "User Creation: Include roles-sap/3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-template
  vars:
    always_upload_jinja_templates:     false
    task_prefix:                       "GENERIC: "
    bom_name:                          "{{ bom_base_name }}"
    sap_cd_package_cd1:
    sap_cd_package_cd2:
    sap_cd_package_cd3:
    sap_cd_package_cd4:
    sap_cd_package_cd5:
    sap_cd_package_hdbclient:
    sap_ciInstanceNumber:
    app_instance_number:
    sap_ciDialogWPNumber:
    sap_ciBtcWPNumber:
    sap_installSAPHostAgent:
    sap_profile_dir:
    sap_scs_hostname:                  "{{ scs_server }}"
    sap_db_hostname:
    sap_ciVirtualHostname:
    sap_appVirtualHostname:
    param_directory:                   "{{ dir_params }}"
    sidadm_uid:                        "{{ sid_to_be_deployed.sidadm_uid }}"
  tags:
    - skip_ansible_lint

- name:                                "User Creation: install variables"
  ansible.builtin.debug:
    msg:
      - "INSTALLED:  {{ users_created.stat.exists }}"
      - "INIFILE:    {{ sap_inifile }}"
      - "PRODUCT ID: {{ bom.product_ids.generic }}"
    verbosity:                         2

- name:                                "User Creation"
  block:

# *====================================4=======================================8
# |  SAP SCS: Install                                                          |
# | 2230669 - System Provisioning Using a Parameter Input File                 |
# *====================================4=======================================8


#
    - name:                            "User Creation: Progress"
      ansible.builtin.debug:
        msg:                           "Start user creation"

    - name:                            "User Creation: SAP OS USERS and Group Creation {{ sid_to_be_deployed }}"
      ansible.builtin.shell: |
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL={{ dir_params }}/{{ sap_inifile }} \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.generic }}                             \
                                                 SAPINST_SKIP_DIALOGS=true                                                            \
                                                 SAPINST_START_GUISERVER=false
      args:
        chdir:                         "{{ target_media_location }}/SWPM"
        creates:                       "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
      environment:
        SAPSYSTEMNAME:                 "{{ sid_to_be_deployed.sid | upper }}"
        TMPDIR:                        "{{ tmp_directory }}/{{ sid_to_be_deployed.sid | upper }}"
      register:                        generic_user_creation
      failed_when:                     generic_user_creation.rc > 0
      tags:
        - skip_ansible_lint

    - name:                            "User Creation: Installation results"
      ansible.builtin.debug:
        var:                           generic_user_creation
      when:                            generic_user_creation.rc > 0

    - name:                            "User Creation: Installation results"
      ansible.builtin.debug:
        msg:                           "User Creation succeeded"
      when:                            generic_user_creation.rc == 0

    - name:                            "User Creation: Cleanup ini file {{ ansible_hostname }}"
      ansible.builtin.file:
        path:                          "{{ dir_params }}/{{ sap_inifile }}"
        state:                         absent

    - name:                            "User Creation: flag"
      ansible.builtin.file:
        path:                          "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
        state:                         touch
        mode:                          0755
      when:                            generic_user_creation.rc == 0

  when:
    - not users_created.stat.exists

- name:                                "User creation status"
  ansible.builtin.debug:
    msg:                               "Users already created"
  when:
    - users_created.stat.exists

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
