# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |         SAP: Register BOM                                                  |
# |         SAP: deploy Generic Parameter file template                        |
# |         SAP: SAP OS USERS and Group Creation                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---

- name:                                "2.5 SAP User - Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile_template:              "generic-inifile-param.j2"
    sap_inifile:                       "{{ bom_base_name }}-generic-{{ sid_to_be_deployed.sid | lower }}-{{ ansible_hostname }}.params"
    dir_params:                        "{{ tmp_directory }}/.{{ sid_to_be_deployed.sid | lower }}-params"

- name:                                "2.5 SAP User - Create directories"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    mode:                              '{{ item.mode }}'
  loop:
    - { mode: '0755', path: '{{ dir_params }}' }
    - { mode: '0755', path: '{{ tmp_directory }}/{{ sid_to_be_deployed.sid | upper }}' }
    - { mode: '0755', path: '/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}' }

- name:                                "2.5 SAP User - reset"
  ansible.builtin.file:
    path:                              "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
    state:                             absent
  when:                                reinstall

- name:                                "2.5 SAP User - check if Completed"
  ansible.builtin.stat:
    path:                              "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
  register:                            users_created

- name:                                "2.5 SAP User - check if installed"
  ansible.builtin.debug:
    var:                               users_created
    verbosity:                         2

- name:                                "2.5 SAP User - Read Bill of Materials for Generic User Creation"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-register
  vars:
    bom_name:                          "{{ bom_base_name }}"
    task_prefix:                       "GENERIC: "
    sa_enabled:                        true
    always_upload_jinja_templates:     false

- name:                                "2.5 SAP User - Template processing: Create ini file {{ sap_inifile }} from {{ sap_inifile_template }}"
  ansible.builtin.template:
    src:                               "{{ sap_inifile_template }}"
    dest:                              "{{ dir_params }}/{{ sap_inifile }}"
    mode:                              0644
    force:                             true
  vars:
    param_directory:                   "{{ dir_params }}"
    sap_sid:                           "{{ sid_to_be_deployed.sid }}"
    this_sidadm_uid:                   "{{ sid_to_be_deployed.sidadm_uid }}"

- name:                                "2.5 SAP User - install variables"
  ansible.builtin.debug:
    msg:
      - "Users created:  {{ users_created.stat.exists }}"
      - "Inifile:        {{ sap_inifile }}"
      - "Product Id:     {{ bom.product_ids.generic }}"
    verbosity:                         2

- name:                                "2.5 SAP User - User Creation"
  block:
    - name:                            "2.5 SAP User - check installation media exists"
      ansible.builtin.stat:
        path:                          "{{ target_media_location }}/SWPM/sapinst"
      register:                        sapinst_found

    - name:                            "ErrorHandling"
      ansible.builtin.fail:
        msg:                           "INSTALL:0001:Unable to find sapinst, please check that the installation media is mounted"
      when: not sapinst_found.stat.exists

    - name:                            "2.5 SAP User - Information"
      ansible.builtin.debug:
        msg:                           "Start user creation"

    - name:                            "2.5 SAP User - SAP OS USERS and Group Creation Ini file {{ sid_to_be_deployed.sid | upper }}"
      ansible.builtin.shell: |
                                       cat {{ dir_params }}/{{ sap_inifile }}
      register:                        generic_user_creation_ini

    - name:                            "2.5 SAP User - Information"
      ansible.builtin.debug:
        var:                           generic_user_creation_ini
        verbosity:                     4

    - name:                            "2.5 SAP User - SAP OS USERS and Group Creation {{ sid_to_be_deployed.sid | upper }}"
      become:                          true
      become_user:                     root
      ansible.builtin.shell: |
                                       umask {{ custom_umask | default('022') }} ;
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL={{ dir_params }}/{{ sap_inifile }}     \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.generic }}            \
                                                 SAPINST_SKIP_DIALOGS=true                                           \
                                                 SAPINST_ENFORCE_CRL={{ sapinst_enforce_crl }}                       \
                                                 SAPINST_START_GUISERVER=false
      args:
        chdir:                         "{{ target_media_location }}/SWPM"
        creates:                       "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
      environment:
        SAPSYSTEMNAME:                 "{{ sid_to_be_deployed.sid | upper }}"
        TMPDIR:                        "{{ tmp_directory }}/{{ sid_to_be_deployed.sid | upper }}"
      register:                        generic_user_creation
      failed_when:                     generic_user_creation.rc > 0

    - name:                            "2.5 SAP User - Installation results"
      ansible.builtin.debug:
        var:                           generic_user_creation
      when:                            generic_user_creation.rc > 0

    - name:                            "2.5 SAP User - Installation results"
      become:                          true
      become_user:                     root
      when:                            generic_user_creation.rc == 0
      block:
        - name:                        "2.5 SAP User - Installation results"
          ansible.builtin.debug:
            msg:                       "User Creation succeeded"

        - name:                        "2.5 SAP User - flag"
          ansible.builtin.file:
            path:                      "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
            state:                     touch
            mode:                      0755

    - name:                            "2.5 SAP User - Cleanup ini file {{ ansible_hostname }}"
      ansible.builtin.file:
        path:                          "{{ dir_params }}/{{ sap_inifile }}"
        state:                         absent

    - name:                            "2.5 SAP User - flag"
      become:                          true
      become_user:                     root
      ansible.builtin.file:
        path:                          "/etc/sap_deployment_automation/{{ sid_to_be_deployed.sid | upper }}/user_created.txt"
        state:                         touch
        mode:                          0755
      when:                            generic_user_creation.rc == 0

  when:
    - not users_created.stat.exists

- name:                                "User creation status"
  ansible.builtin.debug:
    msg:                               "Users already created"
  when:
    - users_created.stat.exists

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
