# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                   Playbook for retrieving the sshkey                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts: localhost
  gather_facts: false
  tags:
  - always


  tasks:
# Specify the active tier for this playbook run
  - set_fact:
      tier:     bom

  - name: Load the SAP parameters
    include_vars: "{{ _workspace_directory }}/sap-parameters.yaml"

  - block:
      - include_role:
          name:     roles-misc/0.2-kv-secrets
    tags:
      - 0.2-kv-secrets
