# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                SAP: Register BOM                                           |
# |         SAP DBLOAD: deploy DBLOAD Parameter file install template          |
# |         SAP DBLOAD: Install                                                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---
- name:                                Set dbload facts for oracle multi-sid
  ansible.builtin.set_fact:
    sap_inifile:                       "{{ bom_base_name }}-{{ item.sid }}-dbload-{{ ansible_hostname }}.params"
    sap_inifile_template:              "{{ bom_base_name }}-dbload-inifile-param.j2"
  when:                                 node_tier == "ORACLE-MULTI-SID"
  loop:                                 "{{ MULTI_SIDS }}"

- name:                                "Create run flag directory"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    state:                             directory
    mode:                              0755

# Temporary block to start the listener due the bug in SWPM DEV version.
#Remove this block after checking with SAP - Action on VP
#Create tnsnames.ora
###########################################START OF THE BLOCK###############################################################
- name:                               "Create the tnsnames file"
  become:                             yes
  become_user:                        oracle
  ansible.builtin.template:
    backup:                           yes
    src:                              tnsnames.j2
    dest:                             "/oracle/RDBMS/{{ anydb_version }}/network/admin/tnsnames.ora"
    mode:                             0644
    force:                            true

- name:                               "Create the tnsnames file"
  become:                             yes
  become_user:                        oracle
  ansible.builtin.template:
    backup:                           yes
    src:                              listener.j2
    dest:                             "/oracle/RDBMS/{{ anydb_version }}/network/admin/listener.ora"
    mode:                             0644
    force:                            true


- name:                                "START THE LISTENER"
  become:                              true
  become_user:                         "oracle"
  ansible.builtin.shell:               lsnrctl start
  args:
    creates:                           /etc/sap_deployment_automation/startlsnrctl.txt
    executable:                        /bin/csh
    
- name:                                create startlsnrctl.txt
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/startlsnrctl.txt
    state:                             touch
    mode:                              0755

###########################################END OF THE BLOCK###############################################################


# - name:                                "SAP DBLOAD reset"
#   ansible.builtin.file:
#     path:                              /etc/sap_deployment_automation/sap_deployment_dbload.txt
#     state:                             absent
#   when:                                reinstall

# - name:                                "SAP DBLOAD: check if installed"
#   ansible.builtin.stat:
#     path:                              /etc/sap_deployment_automation/sap_deployment_dbload.txt
#   register:                            dbload_installed

- name:                                "DBLOAD Install"
  block:

    - name:                            Include 3.3.1-bom-utility role for registering the BoM
      ansible.builtin.include_role:
        name:                          roles-sap/3.3.1-bom-utility
        tasks_from:                    bom-register
      vars:
        bom_name:                      "{{ bom_base_name }}"

    - name:                            Include 3.3.1-bom-utility role
      ansible.builtin.include_role:
        name:                          roles-sap/3.3.1-bom-utility
        tasks_from:                    bom-template
      vars:
        sap_cd_package_hdbclient:      /usr/sap/install/CD_HDBCLIENT/SAP_HANA_CLIENT
        sap_cd_package_cd1:            /usr/sap/install/CD_EXPORT
        sap_cd_package_cd2:
        sap_cd_package_cd3:
        sap_cd_package_cd4:
        sap_cd_package_cd5:
        sap_ciInstanceNumber:
        app_instance_number:
        sap_ciDialogWPNumber:
        sap_ciBtcWPNumber:
        sap_installSAPHostAgent:
        sap_profile_dir:               /sapmnt/{{ sap_sid|upper }}/profile
        sap_scs_hostname:              "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
        sap_db_hostname:               "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"
        sap_ciVirtualHostname:
        sap_appVirtualHostname:
      tags:
        - skip_ansible_lint

# *====================================4=======================================8
#   SAP DBLOAD: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
# *====================================4=======================================8


    - name:                            SAP DBLOAD variables
      ansible.builtin.debug:
        msg:
          - "{{ sap_inifile }}"
          - "{{ bom.product_ids.dbl }}"
        verbosity:                     2

    - name:                            "SAP DBLOAD"
      ansible.builtin.shell: |
                                       set -o errexit
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ bom_base_name }}-{{ item.sid }}-dbload-{{ ansible_hostname }}.params \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.dbl }}                          \
                                                 SAPINST_SKIP_DIALOGS=true                                                     \
                                                 SAPINST_START_GUISERVER=false                                                 \
                                                 SAPINST_ACCEPT_INTERNAL_SIGNATURE=true
                                       touch /etc/sap_deployment_automation/sap_deployment_dbload_{{ item.sid }}.txt
      args:
        chdir:                         /usr/sap/install/SWPM
        creates:                       /etc/sap_deployment_automation/sap_deployment_dbload_{{ item.sid }}.txt
      environment:
        TMPDIR:                        /usr/sap/install/{{ item.sid|upper }}
      register:                        dbload
      failed_when:                     dbload.rc > 0
      loop:                            "{{ MULTI_SIDS }}"
      tags:
        - skip_ansible_lint
    
    # - name:                            "SAP DBLOAD flag"
    #   ansible.builtin.file:
    #     path:                          /etc/sap_deployment_automation/sap_deployment_dbload.txt
    #     state:                         touch
    #     mode:                          0755

  # when:
  #   - not dbload_installed.stat.exists

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
