---

# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM Template File
# <BOM>-scs-inifile-param.j2
#
# -------------------------------------+---------------------------------------8

# ------------------<DEBUGGING>-------------------
- name:                                Parameters
  ansible.builtin.debug:
    msg:
      - "SAP SID              :        {{ sap_sid }}"
      - "Instance Number - SCS:        {% if scs_instance_number is defined %}{{ scs_instance_number }}{% endif %}"
      - "SCS Virtual Hostname :        {% if sap_scs_hostname is defined %}{{ sap_scs_hostname }}{% endif %}"
      - "DB Hostname          :        {% if sap_db_hostname is defined %}{{ sap_db_hostname }}{% endif %}"
      - "FQDN                 :        {{ sap_fqdn }}"
      - "sapadm UID           :        {{ sapadm_uid }}"
      - "sapsys GID           :        {{ sapsys_gid }}"
      - "<sid>adm UID         :        {{ sidadm_uid }}"
    verbosity:                         2
# ------------------</DEBUGGING>------------------

# -------------------------------------+---------------------------------------8
#
# Look for template in the storage account first
#
# -------------------------------------+---------------------------------------8

- name:                                "3.3 BoM Processing: - Set Python version {{ distribution_id }}"
  ansible.builtin.set_fact:
    python_version:                    'python2'

- name:                                "3.3 BoM Processing: - Set Python version {{ distribution_id }}"
  ansible.builtin.set_fact:
    python_version:                    'python3'
  when:                                distribution_id in ['suse15', 'redhat8']

#   0x) Create a directory for parameter files
- name:                                "3.3 BoM Processing: Create a directory"
  ansible.windows.win_file:
    path:                              "{{ param_directory }}"
    state:                             directory

- name:                                "3.3.1 BoM Processing: {{ bom_name }} Download: {{ sap_inifile_template }} from the storage account"
  ansible.builtin.get_url:
    url:                               "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/\
                                        {{ sap_inifile_template }}{% if sapbits_sas_token is not undefined %}?{{ sapbits_sas_token }}{% endif %}"
    dest:                              "{{ download_directory }}/bom/{{ sap_inifile_template }}"
    mode:                              0644
    force:                             true
  delegate_to:                         localhost
  become:                              "{{ bom_processing_become }}"
  register:                            result
  vars:
    ansible_python_interpreter:        "{{ python_version }}"
  when:
    - distribution_id in ['suse15', 'redhat8']
    - not always_upload_jinja_templates

- name:                                "3.3.1 BoM Processing: {{ bom_name }} Download: {{ sap_inifile_template }} from the storage account"
  ansible.builtin.get_url:
    url:                               "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/\
                                        {{ sap_inifile_template }}{% if sapbits_sas_token is not undefined %}?{{ sapbits_sas_token }}{% endif %}"
    dest:                              "{{ download_directory }}/bom/{{ sap_inifile_template }}"
    mode:                              0644
    force:                             true
  delegate_to:                         localhost
  become_user:                         root
  become:                              "{{ bom_processing_become }}"
  register:                            result
  when:
    - distribution_id != 'suse15'
    - distribution_id != 'redhat8'
    - not always_upload_jinja_templates

- name:                                "BOM: Create ini files ({{ bom_base_name }})"
  block:

    - name:                            "Create ini file {{ sap_inifile }} from {{ sap_inifile_template }}"
      ansible.windows.win_template:
        src:                           "{{ download_directory }}/bom/{{ sap_inifile_template }}"
        dest:                          '{{ param_directory }}\{{ sap_inifile }}'
        force:                         true

  when:
    - result is succeeded or result is skipped

# -------------------------------------+---------------------------------------8
#
# Look for template on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

- name:                                "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template on disk"
  block:
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template"
      ansible.builtin.stat:
        path:                          "{{ playbook_dir }}/BOM-catalog/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
      register:                        microsoft_supplied_bom_template
      delegate_to:                     localhost
      become:                          "{{ bom_processing_become }}"

    - name:                            "{{ task_prefix }} Create ini file {{ sap_inifile }}"
      ansible.windows.win_template:
        src:                           "{{ microsoft_supplied_bom_template.stat.path }}"
        dest:                          '{{ param_directory }}\{{ sap_inifile }}'
        force:                         true
      when:                            microsoft_supplied_bom_template.stat.exists

# -------------------------------------+---------------------------------------8
#
# Look for template in archives on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template from archive on disk"
      block:

        - name:                        "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) ini file in archive"
          ansible.builtin.stat:
            path:                      "{{ playbook_dir }}/BOM-catalog/archives/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
          register:                    microsoft_supplied_bom_template_archive
          delegate_to:                 localhost
          become:                      "{{ bom_processing_become }}"

        - name:                        "{{ task_prefix }} Create ini file {{ sap_inifile }}"
          ansible.windows.win_template:
            src:                       "{{ microsoft_supplied_bom_template.stat.path }}"
            dest:                      '{{ param_directory }}\{{ sap_inifile }}'
            force:                     true
          when:                        microsoft_supplied_bom_template_archive.stat.exists
      when:                            not microsoft_supplied_bom_template.stat.exists

  when:                                result is failed or always_upload_jinja_templates

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
