# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

use_AFS:                               "{{ NFS_provider == 'AFS' }}"

scs_virtual_hostname:                  "{{ custom_scs_virtual_hostname | default(sap_sid | lower ~ 'scs' ~ scs_instance_number ~ 'cl1', true) }}"
...
