# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

scs_virtual_hostname:                  "{{ sap_sid | lower }}scs{{ scs_instance_number }}cl1"
ers_virtual_hostname:                  "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"

sapcontrol_command:                    "sapcontrol -nr {{ scs_instance_number }}"

acss_cli_extension_url:                "https://files.pythonhosted.org/packages/ce/f3/91b1a5fdff7a7f0cc8bdfc9a7177f1c1dbab909f857a5ba4cc837650635e/azure_mgmt_workloads-1.0.0-py3-none-any.whl"

...
