---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               Task: 1.3       - Repos per OS                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# For each supported 'distribution_id' we want a list of dictionary entries that
# specify the associated tier (or 'all' to always match), the repository name name
# See the definition of 'distribution_full_id' to determine what to use when
# creating an entry for a new distribution.
# For example, XX.Y where XX is the major version and Y is the minor version
repos:
  redhat7.4:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.6:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.7:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.9:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat8.1:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.2:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.4:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.6:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.8:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.9:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat8.10:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm', state: 'absent' }
  redhat9.0:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm', state: 'absent' }
  redhat9.2:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm', state: 'absent' }
  # do not have any repos that are needed for RedHat at the moment.
  sles_sap12.3:
  sles_sap12.4:
  sles_sap12.5:
  sles_sap15.1:
  sles_sap15.2:
  sles_sap15.3:
  sles_sap15.4:
  sles_sap15.5:
  sles_sap15.6:
  sles15.3:
  sles15.4:
  sles15.5:
  sles15.6:
  # Oracle

  # Adding the entries for Oracle-Linux for testing. cat /etc/oracle-release is the command to get the os version info in Oracle linux.
  oraclelinux8.1:
  oraclelinux8.2:
  oraclelinux8.3:
  oraclelinux8.4:
  oraclelinux8.5:
  oraclelinux8.6:
  oraclelinux8.7:
  oraclelinux8.8:
  oraclelinux8.9:
  oraclelinux8.10:
