---

###########################################################################################
# This file calls the OS specific tasks to configure HANA specific clustering resources  #8
###########################################################################################

# 1. Design the role 5.5.4.0-cluster one into all the actions upto cluster roles defenition including installation
# 2. create a separate task which has common ASCS profile changes actions which could be used for both sles/rhel
# 3. create os based cluster resources yaml where you actually create the cluster resources

# Clustering commands are based on the Host OS

- name:                                "ERS Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_ers.txt
  register:                            ers_installed

- name:                                "SCS HA Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_scs.txt
  register:                            scs_installed

- name:                                "5.6 SCSERS - Cluster based on OS in VM"
  include_tasks:                       "5.6.4.0-cluster-{{ ansible_os_family }}.yml"
  when:                                (not scs_installed.stat.exists) or (not ers_installed.stat.exists)

- name:                                "Post ERS Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_ers.txt
  register:                            post_ers_install

- name:                                "Post SCS HA Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/sap_deployment_scs.txt
  register:                            post_scs_install

- name:                                "5.6 SCSERS - profile"
  include_tasks:                       "5.6.4.1-scsersprofile.yaml"
  when:                                (post_scs_install.stat.exists) and (post_ers_install.stat.exists)

- name:                                "5.6 SCSERS - resources"
  include_tasks:                       "5.6.4.2-sap-resources-{{ ansible_os_family }}.yml"
  when:                                (ersservicehalib is defined) and (scsservicehalib is defined)

...
