---

###########################################################################################
# This file calls the OS specific tasks to configure HANA specific clustering resources  #8
###########################################################################################

# 1. Design the role 5.5.4.0-cluster one into all the actions upto cluster roles defenition including installation
# 2. create a separate task which has common ASCS profile changes actions which could be used for both sles/rhel
# 3. create os based cluster resources yaml where you actually create the cluster resources

# Clustering commands are based on the Host OS
- name:                                "5.6 SCSERS: SCS HA Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation//{{ sap_sid | upper }}/sap_deployment_scs.txt
  register:                            scs_installed
  when:                                ansible_hostname == primary_instance_name

# - name:                                "Wait for SCS check on first node to finish"
#   when:                                ansible_hostname == secondary_instance_name
#   ansible.builtin.set_fact:
#     is_scs_check_complete:             "{{ hostvars[primary_instance_name].scs_installed is defined }}"
#   retries:                             30
#   delay:                               60
#   until:                               is_scs_check_complete

- name:                                "5.6 SCSERS: ERS Install: check if installed"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_ers.txt
  register:                            ers_installed
  when:                                ansible_hostname == secondary_instance_name

# - name:                                "Wait for ERS check on second node to finish"
#   when:                                ansible_hostname == primary_instance_name
#   ansible.builtin.set_fact:
#     is_ers_check_complete:             "{{ hostvars[secondary_instance_name].ers_installed is defined }}"
#   retries:                             30
#   delay:                               60
#   until:                               is_ers_check_complete

- name:                                "5.6 SCSERS: SCS HA Install: check if installed"
  ansible.builtin.set_fact:
    scs_is_installed:                  "{{ hostvars[primary_instance_name].scs_installed.stat.exists | default(false) }}"
    ers_is_installed:                  "{{ hostvars[secondary_instance_name].ers_installed.stat.exists | default(false) }}"

- name:                                "5.6 SCSERS: Cluster based on OS in VM"
  ansible.builtin.include_tasks:
    file:                              "5.6.4.0-cluster-{{ ansible_os_family }}.yml"
    apply:
      become:                          true
      become_user:                     root
      tags:
        - "5.6.4.0-cluster"
  when:
    - not scs_is_installed or not ers_is_installed
    - not use_simple_mount

- name:                                "5.6 SCSERS: Cluster based on OS in VM"
  ansible.builtin.include_tasks:
    file:                              "5.6.4.0-cluster-{{ ansible_os_family }}-SimpleMount.yml"
    apply:
      become:                          true
      become_user:                     root
      tags:
        - "5.6.4.0-cluster-simplemount"
  when:
    - not scs_is_installed or not ers_is_installed
    - use_simple_mount
    - ansible_os_family | upper == "SUSE"

- name:                                "5.6 SCSERS: Post SCS HA Install check if installed"
  become:                              true
  ansible.builtin.stat:
    path:                              "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_scs.txt"
  register:                            post_scs_install
  failed_when:                         not post_scs_install.stat.exists
  when:                                ansible_hostname == primary_instance_name

- name:                                "5.6 SCSERS: Post ERS Install check if installed"
  become:                              true
  ansible.builtin.stat:
    path:                              "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_ers.txt"
  register:                            post_ers_install
  failed_when:                         not post_ers_install.stat.exists
  when:                                ansible_hostname == secondary_instance_name

# introduce throttle to sequence task execution on each node before moving to next task
# did not add the cluster includes in here. May need to consider this here as well.
# ansible.builtin.stat fails with dict object has no attribute 'stat', because the
# dict doesn't have any values as the exec on primary node is skipped and
# registered post_[scs/ers] vars are empty not dictionaries
- name:                                "5.6 SCSERS: Adapt the ASCS/SCS and ERS instance profiles"
  throttle:                            1
  block:

    - name:                            "5.6 SCSERS: SCS cluster group validation"
      ansible.builtin.include_tasks:
        file:                          "5.6.6-validate.yml"
        apply:
          become:                      true
          become_user:                 root
          tags:
            - "5.6.6-validate"

    - name:                            "5.6 SCSERS: SCSERS - profile"
      ansible.builtin.include_tasks:
        file:                          "5.6.4.1-scsersprofile.yaml"
        apply:
          become:                      true
          become_user:                 root
          tags:
            - "5.6.4.1-scsersprofile"

    - name:                            "5.6 SCSERS - SAP resources"
      ansible.builtin.include_tasks:
        file:                          "5.6.4.2-sap-resources-{{ ansible_os_family }}.yml"
        apply:
          become:                      true
          become_user:                 root
          tags:
            - "5.6.4.2-sap-resources"
      when:
        - not use_simple_mount

    - name:                            "5.6 SCSERS - SAP resources"
      ansible.builtin.include_tasks:
        file:                          "5.6.4.2-sap-resources-{{ ansible_os_family }}-SimpleMount.yml"
        apply:
          become:                      true
          become_user:                 root
          tags:
            - "5.6.4.2-sap-resources-simplemount"
      when:
        - use_simple_mount
    # - name:                            "5.6 SCSERS - SAP resources"
    #   ansible.builtin.include_tasks:
    #     file:                          "5.6.4.2-sap-resources-{{ ansible_os_family }}.yml"
    #     apply:
    #       become:                      true
    #       become_user:                 root
    #       tags:
    #         - "5.6.4.2-sap-resources"
  # when:
  #   - ersservicehalib.rc == 0
  #   - scsservicehalib.rc == 0

...
