---

# SLES Clustering - Deploy ASCS/ERS clustering Resources
# Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-rhel-netapp-files


 # [1] Create a virtual IP resource and health-probe for the ASCS instance

- name:                                "5.6 SCSERS - SUSE - SCS - Cluster Configuration before Install "
  throttle:                            1
  block:
    - name :                           "Put Secondary host on standby"
      ansible.builtin.command:         crm node standby {{ secondary_instance_name }}

    - name:                            "5.6 SCSERS - SCS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_{{ instance_type | upper }} Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}{{ instance_type | lower }}{{ scs_instance_number }}' \
                                       directory='{{ profile_directory }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_scs_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_scs_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        ascs_fs_resource
      failed_when:                     ascs_fs_resource.rc > 1

    - name:                            "5.6 SCSERS - SCS - Create ASCS VIP - This is LB frontend ASCS/SCS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_{{ instance_type | upper }} IPaddr2 \
                                       params ip={{ scs_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       op monitor interval="10s" timeout="20s"
      register:                        ascs_vip
      failed_when:                     ascs_vip.rc > 1

    - name:                            "5.6 SCSERS - SCS - create Azure LB resource"
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_{{ instance_type | upper }} azure-lb port=620{{ scs_instance_number }}
      register:                        ascs_lb
      failed_when:                     ascs_lb.rc > 1

    - name:                            "5.6 SCSERS - SCS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_{{ instance_type | upper }} fs_{{ sap_sid }}_{{ instance_type | upper }} nc_{{ sap_sid }}_{{ instance_type | upper }} \
                                       vip_{{ sap_sid }}_{{ instance_type | upper }} meta resource-stickiness=3000
      register:                        ascs_hp
      failed_when:                     ascs_hp.rc > 1
  when: inventory_hostname == primary_instance_name

- name:                                "5.6 SCSERS - SUSE - SCS - Install SCS on Primary host"
  throttle:                            1
  block:
    # [1] Install SAP NetWeaver ASCS - here we can call the SCS installation playbook -
    - name:                            "5.6 SCSERS - SCS - Assign ownership"
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        owner:                         "{{ sap_sid | lower }}adm"
        group:                         sapsys
        recurse:                       true
        state:                         directory
      loop:
        - { path: '/sapmnt/{{ sap_sid | upper }}' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/SYS' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/{{ instance_type | upper }}{{ scs_instance_number }}' }

    - name:                            "5.6 SCSERS - SUSE - SCS - Install SCS on Primary host"
      ansible.builtin.include_role:
        name:                          roles-sap/5.0.1-scs-ha-install
      vars:
        sap_scs_hostname:              "{{ scs_virtual_hostname }}"

    - name:                            "5.6 SCSERS - SUSE - SCS - Check if installation succeeded"
      ansible.builtin.stat:
        path:                          "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_scs.txt"
      register:                        scs_installed

    - name:                            "ErrorHandling"
      ansible.builtin.fail:
        msg:                           "INSTALL:0014:SCS HA installation failed"
      when:
        - not scs_installed.stat.exists
  when: inventory_hostname == primary_instance_name

# [1] Create a virtual IP resource and health-probe for the ERS instance

- name:                                "5.6 SCSERS - SUSE - ERS - Cluster Configuration before Install"
  throttle:                            1
  block:
    - name:                            "5.6 SCSERS - ERS - Bring Secondary host online"
      ansible.builtin.command:         crm node online {{ secondary_instance_name }}
      register:                        secondary_online
      changed_when:                    secondary_online.rc != 0

    - name :                           "5.6 SCSERS - ERS - Put Primary host on standby"
      ansible.builtin.command:         crm node standby {{ primary_instance_name }}
      register:                        primary_standby
      changed_when:                    primary_standby.rc != 0

    - name:                            "5.6 SCSERS - ERS - Configure File system resources"
      ansible.builtin.command: >
                                       crm configure primitive fs_{{ sap_sid }}_ERS Filesystem \
                                       device='{{ sap_mnt }}/usrsap{{ sap_sid }}ers{{ ers_instance_number }}' \
                                       directory='/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' fstype='nfs' options='sec=sys,vers=4.1' \
                                       op start timeout="{{ cluster_sap_scs_timeouts.start }}" interval=0 \
                                       op stop timeout="{{ cluster_sap_scs_timeouts.stop }}"  interval=0 \
                                       op monitor interval="20s" timeout="40s"
      register:                        ers_fs_resource
      failed_when:                     ers_fs_resource.rc > 1

    - name:                            "5.6 SCSERS - ERS - Create ERS VIP - This is LB frontend ERS IP"
      ansible.builtin.command: >
                                       crm configure primitive vip_{{ sap_sid }}_ERS IPaddr2 \
                                       params ip={{ ers_lb_ip }} cidr_netmask={{ subnet_prefix }} \
                                       op monitor interval="10s" timeout="20s"
      register:                        ers_vip
      failed_when:                     ers_vip.rc > 1

    - name:                            "5.6 SCSERS - ERS - create Azure LB resource "
      ansible.builtin.command:         crm configure primitive nc_{{ sap_sid }}_ERS azure-lb port=621{{ ers_instance_number }}
      register:                        ers_alb
      failed_when:                     ers_alb.rc > 1

    - name:                            "5.6 SCSERS - ERS - Create Health Probe"
      ansible.builtin.command: >
                                       crm configure group g-{{ sap_sid }}_ERS fs_{{ sap_sid }}_ERS nc_{{ sap_sid }}_ERS \
                                       vip_{{ sap_sid }}_ERS meta resource-stickiness=3000
      register:                        ers_hp
      failed_when:                     ers_hp.rc > 1
  when: inventory_hostname == secondary_instance_name

    # [2] Install SAP NetWeaver ERS - Create a new playbook for Installation of ERS - done
- name:                                "5.6 SCSERS - SUSE - ERS - Install ERS on Secondary host"
  throttle:                            1
  block:
    - name:                            "5.6 SCSERS - ERS - Assign ownership"
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        owner:                         "{{ sap_sid | lower }}adm"
        group:                         sapsys
        recurse:                       true
        state:                         directory
      loop:
        - { path: '/sapmnt/{{ sap_sid | upper }}' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/SYS' }
        - { path: '/usr/sap/{{ sap_sid | upper }}/ERS{{ ers_instance_number }}' }

    - name:                            "5.6 SCSERS - ERS - Install on Secondary host"
      ansible.builtin.include_role:
        name:                          roles-sap/5.0.2-ers-ha-install
  always:
    - name:                            "5.6 SCSERS - ERS - Bring Primary host online"
      ansible.builtin.command:         "crm node online {{ primary_instance_name }}"
      register:                        primary_online
      changed_when:                    primary_online.rc != 0

    - name:                            "5.6 SCSERS - SUSE - ERS - Check if installation succeeded"
      ansible.builtin.stat:
        path:                          "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_ers.txt"
      register:                        ers_installed

    - name:                            "ErrorHandling"
      ansible.builtin.fail:
        msg:                           "INSTALL:0014:ERS installation failed"
      when:
        - not ers_installed.stat.exists

  when: inventory_hostname == secondary_instance_name


# END of playbook.
...
