# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the Sybase ASE Software installation                |
# |                  Step 4: Create Directories for ASE installation           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Set BOM facts for SAP SYBASE Install

- name:                                "4.3.0.5 - SYBASE Installation - Create sap_deployment_automation folder"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    mode:                              0755
    state:                             directory

- name:                                "4.3.0.5 - SYBASE Installation - Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile:                       "{{ bom_base_name }}-dbload-{{ ansible_hostname }}.params"
    sap_inifile_template:              "dbload-inifile-param.j2"
    dir_params:                        "{{ tmp_directory }}/.{{ sap_sid | upper }}-params"

- name:                                "4.3.0.5 - SYBASE Installation - Create directories"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    mode:                              '{{ item.mode }}'
  loop:
    - { mode: '0755', path: '{{ dir_params }}' }
    - { mode: '0777', path: '{{ tmp_directory }}/{{ sap_sid | upper }}' }
    - { mode: '0755', path: '/etc/sap_deployment_automation/{{ sap_sid | upper }}' }
    - { mode: '0755', path: '/sybase/{{ db_sid | upper }}/sybtemp' }
    - { mode: '0755', path: '/sybase/{{ db_sid | upper }}/sybtemp/data' }
    - { mode: '0755', path: '/sybase/{{ db_sid | upper }}/sybsystem' }


...
