# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

- name:                 "1.13 MOTD - Restart sshd service"
  become:               true
  ansible.builtin.service:
    name:               sshd
    state:              restarted


...
