---
# -------------------------------------+---------------------------------------8
# Step: 01
# Description:
#
- name:                                 "aggregate_bom: - Informational"
  ansible.builtin.debug:
    var:                                bom_dir
    verbosity:                          1
# Step: 01 - END
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 02
# Description:
#
- name:                                 "aggregate_bom: - One time block"
  block:

# -------------------------------------+---------------------------------------8
# Step: 02-01
# Description:  Set Fact
#
    - name:                                 "aggregate_bom: - new bom name"
      ansible.builtin.set_fact:
        new_bom_name:                       "{{ bom_base_name }}-{{ bom_suffix }}"
      when:
        - new_bom_name is not defined

    - name:                                 "Informational"
      ansible.builtin.debug:
        var:                                new_bom_name
        verbosity:                          1
# Step: 02-01 - END
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 02-02
# Description:  Create download directory structure
#
    - name:                                 "aggregate_bom: - Create temporary BOM directories"
      delegate_to:                          localhost
      ansible.builtin.file:
        path:                               "{{ download_directory }}/bom/{{ new_bom_name }}"
        state:                              directory
        mode:                               0755
# Step: 02-02 - END
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 02-03
# Description:  Write aggregated bom
#
    - name:                                "aggregate_bom: - write aggregated BOM"
      delegate_to:                         localhost
      ansible.builtin.copy:
        content:                           "{{ new_bom | default('NOT DEFINED') }}"
        dest:                              "{{ download_directory }}/bom/{{ new_bom_name }}/{{ new_bom_name }}.yaml"
        mode:                              0644
        force:                             true
      register:                            first_pass
# Step: 02-03 - END
# -------------------------------------+---------------------------------------8

  when:
    - first_pass is not defined                                                 # Causes to only be run on first pass when called in a loop
# Step: 02 - END
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 03
# Description:  Find
#
- name:                                 "aggregate_bom: - find files and directories"
  ansible.builtin.find:
    paths:                              "{{ bom_dir.path }}"
    file_type:                          any
    recurse:                            true
  register:                             bom_directory_all_files
# Step: 03 - END
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 04
# Description:  Process file objects
#
- name:                                 "aggregate_bom: - process file objects"
  ansible.builtin.include_tasks:        aggregate_bom_files.yaml
  vars:
    task_prefix:                        aggregate_bom_files
    this_bom_name:                      "{{ bom_dir.path | basename }}"
  loop:                                 "{{ bom_directory_all_files.files | flatten(levels=1) }}"
  loop_control:
    loop_var:                           bom_directory_object
# Step: 04 - END
# -------------------------------------+---------------------------------------8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
