# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

- name:                                "4.1.4 Oracle Data Guard - Observer - Set variables from BoM"
  ansible.builtin.stat:
    path:                               "/etc/systemd/system/sdaf-oracle-fsfo-observer.service"
  register:                            fsfo_observer_service

- name:                                "4.1.3 Oracle Data Guard: - Duplicate the database"
  when:                                not fsfo_observer_service.stat.exists
  ansible.builtin.include_tasks:       "configure.yaml"

- name:                                "4.1.4 Oracle Data Guard - Observer - systemctl enable and start sdaf-oracle-fsfo-observer.service"
  when:                                fsfo_observer_service.stat.exists
  become:                              true
  ansible.builtin.systemd:
    name:                              sdaf-oracle-fsfo-observer.service
    state:                             started

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
