# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the Disk system mounts                              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# Mount Filesystems

- name:                                "2.6.2 Mount - ORACLE - Gather Logical volumes created in 1.5"
  ansible.builtin.include_vars:        disks_config.yml

- name:                                "2.6.2 Mount - ORACLE - Set the NFS Server name list"
  ansible.builtin.set_fact:
    nfs_server_temp:                   "{{ nfs_server_temp | default([]) + [item] }}"
  with_items:
    - "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_SCS') }}"
    - "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_DB') }}"

- name:                                "2.6.2 Mount - ORACLE - Set the NFS Server name"
  ansible.builtin.set_fact:
    nfs_server:                        "{{ nfs_server_temp | first }}"
  when:                                NFS_provider == "NONE"

- name:                                "2.6.2 Mount - ORACLE - Check if  logical volumes exist."
  ansible.builtin.stat:
    path:                              "{{ dev_path_from_lv_item }}"
  loop:                                "{{ logical_volumes }}"
  register:                            oravgstat

- name:                                "2.6.2 Mount - ORACLE - Show oravgstat"
  ansible.builtin.debug:
    var:                               oravgstat
    verbosity:                         2

- name:                                "2.6.2 Mount - ORACLE - Gather existing Logical Volumes"
  ansible.builtin.set_fact:
    lvexists:                          "{{ oravgstat.results | selectattr('stat.exists', 'equalto', true) | map(attribute='item.lv') | list }}"

- name:                                "2.6.2 Mount - ORACLE - Show lvexists"
  ansible.builtin.debug:
    var:                               lvexists
    verbosity:                         2

# Mount Filesystems
- name:                                "2.6.2 Mount - ORACLE - Mount Filesystems for Oracle"
  ansible.posix.mount:
    src:                               "{{ dev_path_from_lv_item }}"
    path: >-
                                       {%- set lv_parts = item.lv.split('_') -%}
                                       {%- if lv_parts| length == 2 -%}
                                       {%- set _path = '/' ~ lv_parts[-1] -%}
                                       {%- else -%}
                                       {%- set _path = ['/' ~ lv_parts[-2], db_sid | upper, lv_parts[-1]] | join('/') -%}
                                       {%- endif -%}
                                       {{- _path -}}
    fstype:                            "{{ item.fstype }}"
    opts:                              defaults
    state:                             mounted
  loop:                                "{{ logical_volumes | sort(attribute='lv') }}"
  register:  oracle_filesystem_mounts
  when:
    - item.node_tier == "oracle"
    - item.lv in  lvexists

- name:                                "2.6.2 Mount - ORACLE - Create sap_deployment_automation folder"
  become:                               true
  become_user:                         root
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    mode:                              0755
    state:                             directory
    owner:                             oracle
    group:                             oinstall

- name:                                "2.6.2 Mount - ORACLE - Make oracle:oinstall as owners"
  become:                               true
  become_user:                         root
  ansible.builtin.file:
    path:                              /oracle
    group:                             oinstall
    owner:                             oracle
    mode:                              0775

- name:                                "2.6.2 Mount - ORACLE - Create filepermission.txt"
  become:                               true
  become_user:                         root
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/filepermission.txt
    mode:                              0755
    state:                             touch

# Mount Filesystems
- name:                                "2.6.2 Mount - ORACLE - Mount SAP File systems on Database for installation"
  ansible.posix.mount:
    src:                               "{{ item.src }}"
    path:                              "{{ item.path }}"
    fstype:                            "{{ item.type }}"
    opts:                              defaults
    state:                             mounted
  vars:
    # Get all the hostnames in <SID>_SCS group and return only the first hostname
    nfs_server:                        "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_SCS') | first }}"
  loop:
    - {typE - 'nfs4',    src: '{{ nfs_server }}:/sapmnt/{{ sap_sid | upper }}',    path: '/sapmnt/{{ sap_sid | upper }}' }
  when:
    - sap_mnt is undefined

# Mount install file system on Observer node.
- name:                                "2.6.2 Mount - ORACLE - Mount Install folder when using AFS"
  ansible.posix.mount:
    src:                               "{{ item.src }}"
    path:                              "{{ item.path }}"
    fstype:                            "{{ item.type }}"
    opts:                              "vers=4,minorversion=1,sec=sys"
    state:                             mounted
  vars:
    # Get all the hostnames in <SID>_SCS group and return only the first hostname
    nfs_server:                        "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_SCS') | first }}"
  loop:
    - { typE - 'nfs4', src: '{{ usr_sap_install_mountpoint }}/{{ bom_base_name }}', path: '{{ target_media_location }}' }
  when:
    - node_tier in ['observer', 'oracle-asm']
    - use_AFS

# Debug for testing
- name:                                "2.6.2 Mount - ORACLE - Print oracle filesystems"
  ansible.builtin.debug:
    var:                               oracle_filesystem_mounts
    verbosity:                         2
