# /*---------------------------------------------------------------------------8
# |                                                                            |
# |         Prepare for the mounts                                             |
# |         Create temporary directory structure                               |
# |         Mount the share, create the directory structure on share           |
# |         Unmount and clean up temporary directory structure                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "ANF Mount: Loop variable"
  ansible.builtin.debug:
    var:                               item
    verbosity:                         2

- name:                                "ANF Mount: HANA {{ item.type }}"
  block:
    - name:                            "ANF Mount: Create /{{ item.temppath }}"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}"
        mode:                          0755
        state:                         directory
        group:                         sapsys

    - name:                            "ANF Mount: ({{ item.type }})"
      block:
        - name:                        "ANF Mount: Filesystems on ANF ({{ item.temppath }})"
          ansible.posix.mount:
            src:                       "{{ item.mount }}"
            path:                      "/{{ item.temppath }}"
            fstype:                    "nfs4"
            opts:                      "{{ item.opts }}"
            state:                      mounted
      rescue:
        - name:                        "ANF Mount: Clear the cache of the nfsidmap daemon (ANF)"
          ansible.builtin.shell: |
            nfsidmap -c

        - name:                        "ANF Mount: Ensure the rpcbind service is restarted"
          ansible.builtin.systemd:
            name:                      rpcbind
            state:                     restarted

    - name:                            "ANF Mount: Create Directories ({{ item.temppath }})"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}/{{ item.folder }}"
        state:                         directory
        mode:                          0755

    - name:                            "ANF Mount: Unmount file systems ({{ item.temppath }})"
      ansible.posix.mount:
        src:                           "{{ item.mount }}"
        path:                          "/{{ item.temppath }}"
        state:                         unmounted

    - name:                            "ANF Mount: Delete locally created SAP Directories ({{ item.temppath }})"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}"
        state:                         absent

    - name:                            "ANF Mount: Cleanup fstab and directory ({{ item.temppath }})"
      ansible.posix.mount:
        src:                           "{{ item.mount }}"
        path:                          "/{{ item.temppath }}"
        fstype:                        "nfs4"
        opts:                          "{{ item.opts }}"
        state:                         absent

  when:
    - item.mount is defined
    - ansible_hostname == primary_host
    - item.create_temp_folders


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the mounts                                          |
# |                Create directories and make them immutable                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "ANF Mount: Create SAP Directories ({{ item.path }})"
  ansible.builtin.file:
    owner:                             '{{ sidadm_uid }}'
    group:                             sapsys
    mode:                              0755
    path:                              "{{ item.path }}"
    state:                             directory
    recurse:                           true
  register:                            is_created_now

  tags:
    - skip_ansible_lint
  when:
    - node_tier in item.target_nodes or item.target_nodes == ['all']

# - name:                                "ANF Mount: Create SAP Directories ({{ item.path }})"
#   ansible.builtin.debug:
#     var:                               is_created_now

- name:                                "ANF Mount: Change attribute only when we create SAP Directories ({{ item.temppath }})"
  become:                              true
  become_user:                         "root"
  ansible.builtin.file:
    path:                              "{{ is_created_now.path }}"
    state:                             directory
    mode:                              0755
    attr:                              i+
  when:
    - node_tier in item.target_nodes or item.target_nodes == "all"
    - is_created_now.changed
    - item.set_chattr_on_dir
  tags:
    - skip_ansible_lint

- name:                                "ANF Mount: ({{ item.path }} on {% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %})"
  ansible.posix.mount:
    src:                               "{% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %}"
    path:                              "{{ item.path }}"
    fstype:                            "nfs4"
    opts:                              "{{ item.opts }}"
    state:                             mounted
  when:
    - node_tier in item.target_nodes or item.target_nodes == ['all']
