# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |         Prepare for the mounts                                             |
# |         Create temporary directory structure                               |
# |         Mount the share, create the directory structure on share           |
# |         Unmount and clean up temporary directory structure                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "2.6.0.1 AFS Mount - Show Loop variable"
  ansible.builtin.debug:
    var:                               item
    verbosity:                         2

- name:                                "2.6.0.1 AFS Mount: First server"
  ansible.builtin.debug:
    msg:                               "Primary host: {{ primary_host }}"

- name:                                "2.6.0.1 AFS Mount - HANA {{ item.type }}"
  when:
                                       - item.mount is defined
                                       - ansible_hostname == primary_host
                                       - item.create_temp_folders
  block:
    - name:                            "2.6.0.1 AFS Mount - Create /{{ item.temppath }}"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}"
        mode:                          "{{ item.permissions }}"
        state:                         directory
        group:                         sapsys

    - name:                            "2.6.0.1 AFS Mount - ({{ item.type }})"
      block:
        - name:                        "2.6.0.1 AFS Mount - Filesystems on AFS ({{ item.temppath }})"
          ansible.posix.mount:
            src:                       "{{ item.mount }}"
            path:                      "/{{ item.temppath }}"
            fstype:                    "nfs4"
            opts:                      "{{ item.opts }}"
            state:                      mounted
      rescue:
        - name:                        "2.6.0.1 AFS Mount - Pause for 15 seconds"
          ansible.builtin.pause:
            seconds:                   15
        - name:                        "2.6.0.1 AFS Mount - Filesystems on AFS ({{ item.temppath }})"
          ansible.builtin.debug:
            msg:                       "Rescue - 2.6.0.1 AFS Mount - Filesystems on AFS ({{ item.temppath }})"

        - name:                        "2.6.0.1 AFS Mount - Filesystems on AFS ({{ item.temppath }})"
          ansible.posix.mount:
            src:                       "{{ item.mount }}"
            path:                      "/{{ item.temppath }}"
            fstype:                    "nfs4"
            opts:                      "{{ item.opts }}"
            state:                      mounted

    - name:                            "2.6.0.1 AFS Mount - Create Directories ({{ item.temppath }})"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}/{{ item.folder }}"
        owner:                         "{{ item.owner }}"
        state:                         directory
        mode:                          "{{ item.permissions }}"

    - name:                            "2.6.0.1 AFS Mount - Unmount file systems ({{ item.temppath }})"
      ansible.posix.mount:
        src:                           "{{ item.mount }}"
        path:                          "/{{ item.temppath }}"
        state:                         unmounted

    - name:                            "2.6.0.1 AFS Mount - Delete locally created SAP Directories ({{ item.temppath }})"
      ansible.builtin.file:
        path:                          "/{{ item.temppath }}"
        state:                         absent

    - name:                            "2.6.0.1 AFS Mount - Cleanup fstab and directory ({{ item.temppath }})"
      ansible.posix.mount:
        src:                           "{{ item.mount }}"
        path:                          "/{{ item.temppath }}"
        fstype:                        "nfs4"
        opts:                          "{{ item.opts }}"
        state:                         absent


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the mounts                                          |
# |                Create directories and make them immutable                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                "2.6.0.1 AFS Mount - Create SAP Directories ({{ item.path }})"
  when:
                                       - node_tier in item.target_nodes or item.target_nodes == ['all']
  ansible.builtin.file:
    owner:                             "{{ item.owner }}"
    group:                             sapsys
    mode:                              "{{ item.permissions }}"
    path:                              "{{ item.path }}"
    state:                             directory
    recurse:                           true
  register:                            is_created_now


- name:                                "2.6.0.1 AFS Mount - Change attribute only when we create SAP Directories ({{ item.temppath }})"
  become:                              true
  become_user:                         "root"
  when:
                                       - node_tier in item.target_nodes or item.target_nodes == "all"
                                       - is_created_now.changed
                                       - item.set_chattr_on_dir
  ansible.builtin.file:
    path:                              "{{ is_created_now.path }}"
    state:                             directory
    mode:                              "{{ item.permissions }}"
    attr:                              i+


- name:                                "2.6.0.1 AFS Mount"
  when:
                                       - single_server or ( node_tier in item.target_nodes or item.target_nodes == ['all'] )
  block:
    - name:                            "2.6.0.1 AFS Mount - Mount ({{ item.path }} on {% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %})"
      ansible.posix.mount:
        src:                           "{% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %}"
        path:                          "{{ item.path }}"
        fstype:                        "nfs4"
        opts:                          "{{ item.opts }}"
        state:                         mounted
  rescue:
    - name:                            "2.6.0.1 AFS Mount - Sleep for 10 seconds and continue with play"
      ansible.builtin.wait_for:
        timeout:                       10

    - name:                            "2.6.0.1 AFS Mount - Mount ({{ item.path }} on {% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %})"
      ansible.posix.mount:
        src:                           "{% if item.create_temp_folders %}{{ item.mount }}/{{ item.folder }}{% else %}{{ item.mount }}{% endif %}"
        path:                          "{{ item.path }}"
        fstype:                        "nfs4"
        opts:                          "{{ item.opts }}"
        state:                         mounted
