# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                Perform the Disk system mounts                              |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# Mount Filesystems

- name:                                "2.6.4 SAP Mount - SYBASE - Get Logical volumes created in 1.5"
  ansible.builtin.include_vars:        disks_config.yml

- name:                                "2.6.4 SAP Mount - SYBASE - Check if  logical volumes exist."
  ansible.builtin.stat:
    path:                              "{{ dev_path_from_lv_item }}"
  loop:                                "{{ logical_volumes }}"
  register:                            sybasevolstat

- name:                                "2.6.4 SAP Mount - SYBASE - Debug - Show volume information"
  ansible.builtin.debug:
    msg:                               "Logical volumes status: {{ sybasevolstat }}"
    verbosity:                         2

- name:                                "2.6.4 SAP Mount - SYBASE - Gather existing Logical Volumes"
  ansible.builtin.set_fact:
    lvexists:                          "{{ sybasevolstat.results | selectattr('stat.exists', 'equalto', true) | map(attribute='item.lv') | list }}"

- name:                                "2.6.4 SAP Mount - SYBASE - Show Current logical volumes"
  ansible.builtin.debug:
    msg:                               "Existing logical volumes: {{ lvexists }}"
    verbosity:                         2

# Mount Filesystems
- name:                                "2.6.4 SAP Mount - SYBASE - Mount Filesystems for SYBASE"
  ansible.posix.mount:
    src:                               "{{ dev_path_from_lv_item }}"
    path: >-
                                        {%- set lv_parts = item.lv.split('_') -%}
                                        {%- if ('sapdata' in lv_parts) and
                                            (lv_parts| length == 4) -%}
                                        {%- set _path = ['/' ~ lv_parts[-3],
                                          db_sid | upper,
                                          lv_parts[-2:] | join('_') ] |
                                          join('/') -%}
                                        {%- elif ('saplog' in lv_parts) and
                                            (lv_parts| length == 4) -%}
                                        {%- set _path = ['/' ~ lv_parts[-3],
                                          db_sid | upper,
                                          lv_parts[-2:] | join('_') ] |
                                          join('/') -%}
                                        {%- elif ('sybdb' in lv_parts) and
                                            (lv_parts| length == 3 ) -%}
                                        {%- set _path = ['/' ~ lv_parts[-2],
                                          db_sid | upper] |
                                          join('/') -%}
                                        {%- else -%}
                                        {%- set _path = ['/' ~ lv_parts[-2],
                                          db_sid | upper, lv_parts[-1]] |
                                          join('/') -%}
                                        {%- endif -%}
                                        {{- _path -}}
    fstype:                            "{{ item.fstype }}"
    opts:                              defaults
    state:                             mounted
  loop:                                "{{ logical_volumes |
                                            sort(attribute='lv') }}"
  register:  sybasefsmounts
  when:
    - item.node_tier == "sybase"
    - item.lv in  lvexists

- name:                                "SYBASE: Create sap_deployment_automation
                                        folder"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    mode:                              0755
    state:                             directory

# Debug - Fail
# - name:                                "SYBASE: fail here"
#   ansible.builtin.fail:
#     msg:                               "Fail after printing lv details"

- name:                                "SYBASE: Make sybsid:sapsys as owners for SYBASE
                                        directories - check flag file"
  ansible.builtin.stat:
    path:                              /etc/sap_deployment_automation/filepermission.txt
  register:                            sybase_permissions_set

- name:                                "2.6.4 SAP Mount - SYBASE - Make syb<sid>:sapsys as owners for SYBASE directories"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    owner:                             "{{ item.owner }}"
    group:                             "{{ item.group }}"
    recurse:                           true
    mode:                              u=rwX,g=rX,o=rX
  loop:
    - { path: '/sybase', group: '{{ sapsys_gid }}', owner: '{{ asesidadm_uid }}' }
  when:
    - not sybase_permissions_set.stat.exists

- name:                                "2.6.4 SAP Mount - SYBASE - Create sap_deployment_automation
                                        folder"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    mode:                              0755
    state:                             directory

- name:                                "SYBASE: Create filepermission.txt"
  become:                              true
  become_user:                         root
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/filepermission.txt
    mode:                              0644
    state:                             touch

- name:                                "2.6.4 SAP Mount - SYBASE - Set NFS Server variable"
  ansible.builtin.set_fact:
    nfs_server:                        "{{ query('inventory_hostnames', '{{ sap_sid | upper }}_SCS') | first }}"
  when:
    - NFS_provider == "NONE"
    - sap_mnt is not defined
    - node_tier != 'scs'
    - node_tier in ['pas', 'app', 'ers', 'oracle', 'db2', 'sybase']

- name:                                "2.6.4 SAP Mount - SYBASE - Set NFS Mount variable"
  ansible.builtin.set_fact:
    sapmnt_nfs_mount: >-
                                        {% if (NFS_provider == 'AFS' or NFS_provider == 'ANF') and (sap_mnt is defined) %}{{ sap_mnt }}{% else %}{{ nfs_server }}:/sapmnt/{{ sap_sid | upper }}{% endif %}
  when:
    - (nfs_server is defined and nfs_server != ansible_hostname) or nfs_server is not defined

- name:                                "2.6.4 SAP Mount - SYBASE - Debug NFS Mount variable"
  ansible.builtin.debug:
    var:  sapmnt_nfs_mount
  when:
    - sapmnt_nfs_mount is defined

- name:                                "SYBASE: Set NFS Server options"
  ansible.builtin.set_fact:
    sapmnt_nfs_opts: >-
                                        {% if (NFS_provider == 'AFS' or NFS_provider == 'ANF') and (sap_mnt is defined) %}rw,hard,rsize=65536,wsize=65536,sec=sys,vers=4.1,tcp{% else %}defaults{% endif %}

- name:                                "2.6.4 SAP Mount - SYBASE - Set NFS Server options"
  ansible.builtin.debug:
    var:  sapmnt_nfs_opts

# Mount Filesystems
- name:                                "2.6.4 SAP Mount - SYBASE - Mount SAP Filesystems on Database for installation"
  ansible.posix.mount:
    src:                               "{{ item.src }}"
    path:                              "{{ item.path }}"
    fstype:                            "{{ item.type }}"
    opts:                              "{{ item.opts }}"
    state:                             mounted
  loop:
    - {   tier: 'sybase'
          , type: 'nfs4'
          , src: '{{ sapmnt_nfs_mount }}'
          , path: '/sapmnt/{{ sap_sid | upper }}'
          , opts: '{{ sapmnt_nfs_opts }}'
    }
  when:
    - item.tier == "sybase"
    - sap_mnt is undefined
    - sapmnt_nfs_mount is defined

# Debug for testing
- name:                                "2.6.4 SAP Mount - SYBASE - Print filesystems"
  ansible.builtin.debug:
    msg:                               "SYBASE file systems mounted : {{ sybasefsmounts }}"
    verbosity:                         2

...
