# Defaults for roles-os/1.4-packages

distro_name: "{{ ansible_distribution | upper }}-{{ ansible_distribution_major_version }}"
distribution_id: "{{ ansible_distribution | lower ~ ansible_distribution_major_version }}"
distribution_full_id: "{{ ansible_distribution | lower ~ ansible_distribution_version }}"
distro_family: "{{ ansible_os_family | upper }}"
