# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# ---

- name:                                "2.10 SAP Note - Reboot after the selinux is configured"
  become:                              true
  become_user:                         root
  ansible.builtin.reboot:
    reboot_timeout:                    300
    post_reboot_delay:                 10
  failed_when:                         false
#
- name:                                "2.10 SAP Note - Clear the failed state of hosts"
  ansible.builtin.meta:                clear_host_errors

# Wait for Connection after reboot
- name:                                "2.10.2 SAP Note - Wait for system to become reachable"
  ansible.builtin.wait_for_connection:
    delay:                             10
    timeout:                           300
