# -------------------------------------+---------------------------------------------------------------8
#   DB2 - High Availabiliy Setup                                                                                       |
#     a. Install DB2 on Primary Server                                                                               |
#     b. Take offline backup of Primary DB                                                                        |
#     c.  Install DB2 on Secondary Server using backup restore option                             |
#     d. Rrestore Secondary/Standby from backup of primary system                                |
#     e. HADR  parameters on primary and secodary                                                        |
#     f. HADR definition on primary & Secondary                                                             |
#     g. HADR setup Checks                                                                                                 |

---
# +------------------------------------4--------------------------------------*/
# +                                                                           */
# +                                                                           */
# +            Set the environment variable as sourcing breaks                */
# +            when running from Azure DevOps                                 */
# +                                                                           */
# +------------------------------------4--------------------------------------*/

- name:                                "DB2 Primary System Setup"
  block:

    - name:                            "DB2 Primary System Install"
      ansible.builtin.import_tasks:    4.2.1.0-db2_ha_install_primary.yml

    - name:                            "DB2 - Take offline backup of Primary DB"
      ansible.builtin.import_tasks:    4.2.1.1-db2_primary_backup.yml
  always:
    - name:                            "DB2 Primary System Install: result"
      ansible.builtin.debug:
        var:                           db2_installation
        verbosity:                     4

    - name:                            "DB2 Primary System Install: result"
      ansible.builtin.fail:
        msg:                           db2_installation.stdout_lines
      when:                            db2_installation.rc != 0

  when:
    - ansible_hostname == primary_instance_name

- name:                                "DB2 Secodary System Setup"
  block:

    - name:                            "DB2 Secondary System Install "
      ansible.builtin.import_tasks:    4.2.1.2-db2_ha_install_secondary.yml

    - name:                            "DB2 - Restore Secondary with backup of Primary DB"
      ansible.builtin.import_tasks:    4.2.1.3-db2_restore_secondary.yml
  always:
    - name:                            "DB2 Secondary System Install: result"
      ansible.builtin.debug:
        var:                           db2_installation
        verbosity:                     4

    - name:                            "DB2 Primary System Install: result"
      ansible.builtin.fail:
        msg:                           db2_installation.stdout_lines
      when:                            db2_installation.rc != 0
  when:
    - ansible_hostname == secondary_instance_name

- name:                                "DB2 - Apply high availability database parameters on Primary & Secondary System"
  ansible.builtin.import_tasks:        4.2.1.4-db2_haparameters.yaml

- name:                                "DB2 - Activate HADR on Secondary followed by HADR on Primary"
  ansible.builtin.import_tasks:        4.2.1.5-db2_enable_hadr.yaml

- name:                                "DB2 - HA Configuration Post Install Checks"
  ansible.builtin.import_tasks:        4.2.1.6-db2_post_install_checks.yaml

- name:                                "DB2 - HA Configuration Post Install Profile update"
  ansible.builtin.import_tasks:        4.2.1.7-sap-profile-changes.yaml


# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
