---
name:    'Oracle19_v0003ms'
target:  'Oracle 19'
version: 3
platform: "ORACLE"
# New SBP Patch included  in this version

materials:

  media:
    - name:         Oracle Client
      archive:      51055071.ZIP
      checksum:     d63ba8bf707f96782101d66cbde9677a8bc11b9cfcfc6bbd167b6728c0243806
      extract:      true
      extractDir:   oraclient
      path:         download_basket
      download:     true
      url:          https://softwaredownloads.sap.com/file/0030000001424202021


    - name:         Oracle Software Server
      archive:      51053828.ZIP
      checksum:     a12e10404572813ce78862c34ce3d1288b67ebbffa12fbd6fe758a6743773154
      extract:      true
      download:     true
      extractDir:   oraserver
      path:         download_basket
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0030000002299742019          #Not all S-users have permissions to download the oracle software.


#SBP Patches are downloaded based on SAP Note 2799920 - Patches 19c: Database

    - name:         "Oracle SBP - Bundle patches for 19c: GIRU"
      archive:      GIRU19P_2202-70004508.ZIP
      checksum:     578799a0d7d727b131b410674696afec5762b32afef03a22521a012df2f8cdd9
      extract:      false
      download:     true
      extractDir:   SBP/GIRU19P
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000223642022

    - name:         "Oracle SBP - Bundle patches for 19c: SAP19P"
      archive:      SAP19P_2202-70004508.ZIP
      checksum:     4a231da93010f1d700d89cde8c05f5be8c50fc85ce3843156123765271274815
      extract:      true
      extractDir:   SBP/SAPSBP
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000219572022

    - name:         "Oracle SBP - Bundle patches for 19c: SBPJDK19P"
      archive:      SBPJDK19P_2202-70004508.ZIP
      checksum:     e411cddd92e21ed21348ea0da146fa08bbfe9a39b1c955fff532df785bd666b6
      extract:      false
      extractDir:   SBP/SBPJDK
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000219812022

    - name:         "Oracle SBP - Bundle patches for 19c: OPatch"
      archive:      OPATCH19P_2202-70004508.ZIP
      checksum:     b1860114866acf5bcd9497804ec84957f74abadca730ebc54d7f324c5b656b53
      extract:      true
      extractDir:   SBP/OPATCH
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000226172022


    - name:         "Oracle compact-lib"
      archive:      compat-libcap1-1.10-7.el7.x86_64.rpm
      extract:      false
      checksum:     30FB28F1266049493E5AEFFE18E8939B1BB4A889F1013EBEF6DABE496156B501
      url:          https://public-yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/compat-libcap1-1.10-7.el7.x86_64.rpm

    - name:         "Oracle ASMSUPPORT RPM"
      archive:      oracleasm-support-2.1.12-1.el8.x86_64.rpm
      extract:      false
      checksum:     A60037BEECBF5CC95957CB04ED7CDF511867FE8F65CFD014033FCEFC3BB29C0C
      url:          https://public-yum.oracle.com/repo/OracleLinux/OL8/addons/x86_64/getPackage/oracleasm-support-2.1.12-1.el8.x86_64.rpm

    - name:         "Oracle ASMLIB RPM"
      archive:      oracleasmlib-2.0.17-1.el8.x86_64.rpm
      extract:      false
      checksum:     0ABF6BD267E67C472D194DBBEFC723D3A1910AAF8D688FAE4BB6980CE1F3281A
      url:          https://download.oracle.com/otn_software/asmlib/oracleasmlib-2.0.17-1.el8.x86_64.rpm

...
