---
name:    'HANA_2_00_055_v0006ms'
target:  'HANA 2.0'
version: 6
platform: 'HANA'

materials:

  media:
    # SAPCAR 7.22
    - name:         "SAPCAR 7.22; OS: Linux on x86_64 64bit"
      archive:      SAPCAR_1115-70006178.EXE
      checksum:     765412436934362cc5497e3d659fbb78be91093a091c11ec4fbe84dfb415a0e5
      filename:     SAPCAR
      permissions:  '0755'
      url:          https://softwaredownloads.sap.com/file/0020000000098642022

    # HANA Client v2.9
    - name:         SAP HANA CLIENT Version 2.9
      archive:      IMDB_CLIENT20_009_28-80002082.SAR
      checksum:     22f1db5fe4163f4e6d5ebdf2cd4e4a6269cb8cbced2df26988460ab054ddc587
      extract:      true
      extractDir:   CD_HDBCLIENT
      creates:      SIGNATURE.SMF
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000001117022021

    # v2_00_059 Revision 2.00.059.2 (SPS05) for HANA DB 2.0
    - name:         HANA Server
      archive:      IMDB_SERVER20_059_2-80002031.SAR
      checksum:     743c91d641eff6a237473bd0d7630fd0db6ac04ad9febfe50ffc6d100f3ecb80
      extract:      true
      extractDir:   CD_HDBSERVER
      creates:      SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000401402022

    - name:         SAP HANA AFL Rev 59.100 only for HANA 2.0 Rev 59.01
      archive:      IMDB_AFL20_059P_100-80001894.SAR
      checksum:     5e35a4ca42b7d98853eebe1288ed77a7209717d24bf9ae0130926fd5bacbafa3
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_AFL/packages
      url:          https://softwaredownloads.sap.com/file/0020000000064932022

    - name:         LCAPPS for HANA 2.00.059.00
      archive:      IMDB_LCAPPS_2059P_100-20010426.SAR
      checksum:     561318bf34896d97918878cb68729c7f2c6451d89182e95ea7020b1df074bc1d
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_LCAPPS/packages
      url:          https://softwaredownloads.sap.com/file/0020000000064992022

    - name:         VCH AFL 1909 Rev 59.100 only for HANA 2.0 Rev 59.01
      archive:      VCH190900_2059P_100-80004631.SAR
      checksum:     a3dff8122596b1cd461ec873d9597ac1086d75381426366b6e619b27a02369b4
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/VCH_AFL_1909/packages
      url:          https://softwaredownloads.sap.com/file/0020000000065082022

    - name:         AP HOST AGENT 7.22 SP54
      archive:      SAPHOSTAGENT54_54-80004822.SAR
      checksum:     5899a0934bd8d37a887d0d67de6ac0520f907a66ff7c3bc79176fff99171a878
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000001542872021

    - name:         SAPHostAgent RPM Package
      archive:      saphostagentrpm_54-80004822.rpm
      checksum:     36e07aa24b0dca972f9bfeff5757ca52f693d34f013818b171aa684b3aef1d98
      url:          https://softwaredownloads.sap.com/file/0020000001305892021


...
