# /*---------------------------------------------------------------------------8
# |                                                                            |
# |             SAP: Register BOM                                              |
# |         SAP APP: deploy APP Parameter file install template                |
# |         SAP APP: Install                                                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---
- name:                                "APP Install: Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile:                       "{{ bom_base_name }}-app-{{ sap_sid }}-{{ ansible_hostname }}.params"
    sap_inifile_template:              "{{ bom_base_name }}-app-inifile-param.j2"
    dir_params:                        "{{ tmp_directory }}/.{{ sap_sid | lower }}-params"

#   0x) Create hidden directory for parameter files
- name:                                "APP Install: Create hidden directory"
  ansible.builtin.file:
    path:                              "{{ item.path }}"
    state:                             directory
    mode:                              '{{ item.mode }}'
  loop:
    - { state: 'directory', mode: '0755', path: '{{ dir_params }}' }

- name:                                "APP Install: Create run flag directory"
  ansible.builtin.file:
    path:                              "/etc/sap_deployment_automation/{{ sap_sid | upper }}"
    state:                             directory
    mode:                              0755

- name:                                "APP Install: reset"
  ansible.builtin.file:
    path:                              "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_app.txt"
    state:                             absent
  when:                                reinstall

- name:                                "APP Install: check if installed"
  ansible.builtin.stat:
    path:                              "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_app.txt"
  register:                            app_installed

- name:                                "APP Install: Get the SCS Server name list"
  ansible.builtin.set_fact:
    scs_server_temp:                   "{{ scs_server_temp | default([]) + [item] }}"
  with_items:
    - "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') }}"
    - "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB') }}"

- name:                                "APP Install: Set the SCS Server name"
  ansible.builtin.set_fact:
    scs_server:                        "{% if scs_high_availability %}{{ sap_sid | lower }}scs{{ scs_instance_number }}cl1{% else %}{{ scs_server_temp | first }}{% endif %}"
    db_virtual_host:                   "{% if db_high_availability %}{{ sap_sid | lower }}{{ db_sid | lower }}db{{ hdb_instance_number }}cl{% else %}{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}{% endif %}"
    file_path:                         "{% if scs_high_availability %}INSTALL/HA/ABAP/APPX{% else %}INSTALL/DISTRIBUTED/ABAP/APPS{% endif %}"

- name:                                "APP Install: Include 3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-register
  vars:
    bom_name:                          "{{ bom_base_name }}"
    task_prefix:                       "APP Install: "

- name:                                "APP Install: Include roles-sap/3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-template
  vars:
    task_prefix:                       "APP Install: "
    always_upload_jinja_templates:     false
    bom_name:                          "{{ bom_base_name }}"
    sap_cd_package_hdbclient:          "{{ target_media_location }}/CD_HDBCLIENT/SAP_HANA_CLIENT"
    sap_cd_package_cd1:                "{{ target_media_location }}/CD_EXPORT"
    sap_cd_package_cd2:
    sap_cd_package_cd3:
    sap_cd_package_cd4:
    sap_cd_package_cd5:
    sap_ciInstanceNumber:             "{{ scs_instance_number }}"
    app_instance_number:
    sap_ciDialogWPNumber:              12
    sap_ciBtcWPNumber:                 8
    sap_installSAPHostAgent:           "false"
    sap_profile_dir:                   /sapmnt/{{ sap_sid|upper }}/profile
    sap_scs_hostname:                  "{{ scs_server }}"
    sap_db_hostname:                   "{{ db_virtual_host }}"
    sap_ciVirtualHostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_APP') | first }}"
    sap_appVirtualHostname:            "{{ inventory_hostname }}"
    param_directory:                   "{{ dir_params }}"
  tags:
    - skip_ansible_lint

- name:                                "App install: register variables"
  ansible.builtin.set_fact:
    app_bom_id:                        "{{ bom.product_ids.app }}"

- name:                                "App Install: install variables"
  ansible.builtin.debug:
    msg:
      - "INSTALLED:  {{ app_installed.stat.exists }}"
      - "INIFILE:    {{ sap_inifile }}"
      - "PRODUCT ID: {{ bom.product_ids.app }}"
      - "DBHOST:     {{ db_virtual_host }}"

- name:                                "App Install: Set hdbuserstore path"
  ansible.builtin.set_fact:
    hdbuserstore_path:                 "/usr/sap/{{ sap_sid|upper }}/SYS/exe/uc/linuxx86_64/hdbclient"
  when:
    - db_high_availability
    - platform == 'HANA'

- name:                                "APP Install"
  block:

# *====================================4=======================================8
#   SAP APP: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
    - name:                            "APP Install: progress"
      ansible.builtin.debug:
        msg:                           "Starting App Install"

    - name:                            "APP Install: Running sapinst"
      ansible.builtin.shell: |
                                       export SAPSYSTEMNAME={{ sap_sid | upper }};
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL={{ dir_params }}/{{ sap_inifile }}  \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ app_bom_id }}                      \
                                                 SAPINST_SKIP_DIALOGS=true                                        \
                                                 SAPINST_START_GUISERVER=false
      args:
        chdir:                         "{{ target_media_location }}/SWPM"
        creates:                       "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_app.txt"
      environment:
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"
        TMPDIR:                        "{{ tmp_directory }}"
      register:                        app_installation
      failed_when:                     app_installation.rc > 0
      tags:
        - skip_ansible_lint

    - name:                            "APP Install: Installation results"
      ansible.builtin.debug:
        var:                           app_installation
      when:                            app_installation.rc > 0

    - name:                            "APP Install: Installation results"
      ansible.builtin.debug:
        msg:                           "APP Installation succeeded"
      when:                            app_installation.rc == 0

    - name:                            "APP Install: Cleanup ini file {{ ansible_hostname }}"
      ansible.builtin.file:
        path:                          "{{ dir_params }}/{{ sap_inifile }}"
        state:                         absent

    - name:                            "APP Install: Find the installationSuccesfullyFinished.dat (SAPINST)"
      ansible.builtin.find:
        paths:                         "{{ tmp_directory }}/sapinst_instdir/{{ bom.product_ids.app.replace('.','/').replace('/ABAP','').split(':')[1] }}/{{ file_path }}"
        file_type:                     file
        patterns:                      'installationSuccesfullyFinished.dat'
        recurse:                       true
      register:                        app_installed_according_to_sapinst

    - name:                            "APP Install: Set DB Virtual Host name"
      ansible.builtin.shell: |
                                       {{ hdbuserstore_path }}/hdbuserstore SET DEFAULT {{ db_virtual_host }}:30313@{{ db_sid | upper }} {{ hana_schema }} {{ main_password }}
      environment:
        SAPSYSTEMNAME:                 "{{ sap_sid | upper }}"
        TMPDIR:                        "{{ hdbuserstore_path }}"
      register:                        hdbuserstore
      tags:
        - skip_ansible_lint
      when:
        - db_high_availability
        - platform == 'HANA'
        - app_installed_according_to_sapinst is defined
        - app_installed_according_to_sapinst | length > 0

    - name:                            "APP Install: flag"
      ansible.builtin.file:
        path:                          "/etc/sap_deployment_automation/{{ sap_sid | upper }}/sap_deployment_app.txt"
        state:                         touch
        mode:                          0755
      when:
        - app_installation.rc == 0
        - app_installed_according_to_sapinst is defined
        - app_installed_according_to_sapinst | length > 0

  when:
    - not app_installed.stat.exists

- name:                                "APP Install: - status"
  block:

    - name:                            "APP Install: - status"
      ansible.builtin.debug:
        msg:                           "APP Installation is already performed"

    - name:                            "APP Install: - return value"
      ansible.builtin.set_fact:
        app_already_installed:         true

    - name:                            "APP Install: Set DB Virtual Host name"
      ansible.builtin.shell: |
                                       {{ hdbuserstore_path }}/hdbuserstore SET DEFAULT {{ db_virtual_host }}:30313@{{ db_sid | upper }} {{ hana_schema }} {{ main_password }}
      environment:
        SAPSYSTEMNAME:                 "{{ sap_sid | upper }}"
        TMPDIR:                        "{{ hdbuserstore_path }}"
      register:                        hdbuserstore
      tags:
        - skip_ansible_lint
      when:
        - db_high_availability
        - platform == 'HANA'

  when:
    -  app_installed.stat.exists

# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
