# /*---------------------------------------------------------------------------8
# |                           HANA utility commands                            |
# +------------------------------------4--------------------------------------*/

sapcontrol_command:                    "/usr/sap/{{ db_sid | upper }}/HDB{{ hdb_instance_number }}/exe/sapcontrol -nr {{ hdb_instance_number }}"

hana_stop_start_timeout_in_seconds:    2700
hana_stop_start_delay_in_seconds:      2
