# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

- name:                                "1.3 Repository - RHEL- Ensure yum repos are configured on Redhat VMs"
  block:
    - name:                            "1.3 Repository - RHEL - Check that yum repos are registered"
      ansible.builtin.command:         yum repolist # noqa: command-instead-of-module
