# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

# /*---------------------------------------------------------------------------8
# | Prepare the sql script  for  data guard initial configuration.             |
# |                                                                            |
# |                                                                            |
# | Step 1 create the SQL scripts for DG                                       |
# +------------------------------------4--------------------------------------*/

# Set Primary and Secondary node names.

- name:                                "Oracle Data Guard: Setting the primary and Secondary DB names"
  ansible.builtin.set_fact:
    ora_primary:                       "{{ ansible_play_hosts_all[0] }}"         # Oracle Primary Host
    ora_secondary:                     "{{ ansible_play_hosts_all[1] }}"         # Oracle Secondary Host
    current_host:                      "{{ ansible_hostname }}"
  when:
    - node_tier in ["oracle", "oracle-asm"]
    - ansible_play_hosts_all | length > 1

- name:                                "Oracle Data Guard - Preparation Create password file"
  become:                              true
  become_user:                         "{{ oracle_user_name }}"
  ansible.builtin.shell:               "orapwd file=$ORACLE_HOME/dbs/orapw{{ db_sid | upper }} password={{ oracle_password }} entries=5"
  environment:
    ORACLE_SID:                        "{{ db_sid | upper }}"
    ORACLE_HOME:                       "/oracle/{{ db_sid | upper }}/{{ ora_version }}"
  args:
    creates:                           /oracle/{{ db_sid | upper }}/{{ ora_version }}/dbs/orapw{{ db_sid | upper }}
    chdir:                             /etc/sap_deployment_automation/dgscripts
    executable:                        /bin/csh

- name:                                "Oracle Data Guard: Prepare secondary node"
  ansible.builtin.include_tasks:       "ora-dg-secondary-preparation.yaml"
  when:
    - node_tier in ["oracle", "oracle-asm"]
    - action == 'Prepare_Secondary'

- name:                                "Oracle Data Guard: Prepare and Restore"
  block:
    - name:                            "Oracle Data Guard: Preparation tasks"
      ansible.builtin.include_tasks:   "ora-dg-preparation.yaml"

    - name:                            "Oracle Data Guard: Setup primary"
      ansible.builtin.include_tasks:   "ora-dg-setup-primary.yaml"
      when:
        - current_host == ora_primary

    - name:                            "Oracle Data Guard: Setup secondary"
      ansible.builtin.include_tasks:   "ora-dg-setup-secondary.yaml"
      when:
        - current_host == ora_secondary
  when:
    - action    == 'Prepare_and_Restore'
    - node_tier == "oracle" or node_tier == "oracle-asm"
    - node_tier != "observer"

- name:                                "Oracle Data Guard: Post processing on Primary"
  ansible.builtin.include_tasks:       "ora-dg-postprocessing-primary.yaml"
  when:
    - node_tier == "oracle" or node_tier == "oracle-asm"
    - node_tier != "observer"
    - action    == 'Post_Processing_Primary'

# Enable Flashback Logging on the Secondary for FSFO
- name:                                "Oracle Data Guard: Post processing on Secondary"
  ansible.builtin.include_tasks:       "ora-dg-postprocessing-secondary.yaml"
  when:
    - node_tier == "oracle" or node_tier == "oracle-asm"
    - node_tier != "observer"
    - action    == 'Post_Processing_Secondary'

# Enable Flashback Loggining on the Secondary for FSFO
- name:                                "Oracle Data Guard: Post processing on Secondary"
  ansible.builtin.include_tasks:       "ora-dg-postprocessing-secondary.yaml"
  when:
    - node_tier == "oracle" or node_tier == "oracle-asm"
    - node_tier != "observer"
    - action    == 'Post_Processing_Secondary'

# FSFO is enabled from the Observer.
- name:                                "Oracle Data Guard: Setup Observer"
  ansible.builtin.include_tasks:       "ora-dg-observer-setup.yaml"
  when:
    - node_tier == "observer"
    - action    == 'Setup_Observer'
...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
