# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

iscsi_object:                          iqn.2006-04

iscsi_port:                            3260

sapcontrol_command:                    "sapcontrol -nr {{ db_instance_number }}"

# minimum version numbers supported by SAPHanaSR-angi
min_hana_major_version:                2
min_hana_minor_version:                0
min_hana_sps_level:                    50
min_saphanaSR_version:                 "0.153"
min_saphanaSR_version_suschk:          "0.161.1_BF"

# RHEL: Check maintenance mode command based on OS version
pcs_check_maintenance_mode: >-
                                       {% if ansible_distribution_major_version is version ('10','<') %}
                                       pcs property show maintenance-mode
                                       {% else %}
                                       pcs property config maintenance-mode
                                       {% endif %}"
