---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               Task: 1.16       - Services lists per OS & based on SAP node |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# For each supported 'distribution_id' we want a list of dictionary entries that
# specify the associated tier (or 'all' to always match), the service name,
# and whether we want the service to be enabled and started or disabled
# and stopped. See the definition of 'distribution_id' to determine what to use when
# creating an entry for a new distribution.
# In this list one can specify the custom list of services to be enabled,disabled
# OR started, stopped

# Example - Add a line specifying the service, SAP node teir & state
# redhat8:
#      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' }

# -------------------------------------+---------------------------------------8
#
# TODO     - Add specific rules instead of disabling firewalld
#
# -------------------------------------+---------------------------------------8
services:
  redhat7:
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'disabled'  }
    - { tier: 'sapos',       service: 'rpcbind',      node_tier: 'scs',     state: 'started'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'started'   }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'all',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'all',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'enabled'   }

  redhat8:
    - { tier: 'os',          service: 'auditd',       node_tier: 'all',     state: 'started'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'disabled'  }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'started'   }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'hana',    state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'hana',    state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'scs',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'scs',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'ers',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'ers',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'enabled'   }
    - { tier: 'os',          service: 'oddjobd',      node_tier: 'all',     state: 'disabled'  }

  redhat9:
    - { tier: 'os',          service: 'auditd',       node_tier: 'all',     state: 'started'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'disabled'  }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'started'   }
    - { tier: 'sapos',       service: 'tuned',        node_tier: 'all',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'hana',    state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'hana',    state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'scs',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'scs',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'ers',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'ers',     state: 'enabled'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'started'   }
    - { tier: 'ha',          service: 'pcsd',         node_tier: 'db2',     state: 'enabled'   }

  sles_sap12:
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }

  sles_sap15:
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }
    # --------------------------- Begin - Packages required for iSCSI -----------------------------------------8
    # https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-pacemaker#sbd-with-an-iscsi-target-server
    - { tier: 'iscsi',        service: 'targetcli',    node_tier: 'iscsi',   state: 'enabled'   }
    - { tier: 'iscsi',        service: 'targetcli',    node_tier: 'iscsi',   state: 'started'   }
    # ---------------------------- End - Packages required for iSCSI ------------------------------------------8

  oraclelinux8:
    - { tier: 'os',          service: 'auditd',       node_tier: 'all',     state: 'started'   }
    - { tier: 'os',          service: 'oddjobd',      node_tier: 'all',     state: 'disabled'  }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'fstrim.timer', node_tier: 'all',     state: 'disabled'  }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'stopped'   }
    - { tier: 'os',          service: 'firewalld',    node_tier: 'all',     state: 'disabled'  }
    - { tier: 'os',          service: 'waagent',      node_tier: 'all',     state: 'restarted' }  # Ensure the service is restarted and swap space is available in case the handler is not called in 1.1/swap.
    - { tier: 'sapos',       service: 'rpcbind',      node_tier: 'scs',     state: 'restarted' }
