# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# -------------------------------------+---------------------------------------8
#                                                                              |
# Defines the parameters and variables for the Control Plane                   |
#                                                                              |
# -------------------------------------+---------------------------------------8

parameters:
  - name:                              deployer
    displayName:                       "Deployer configuration name, use the following syntax: ENV-LOCA-VNET-INFRASTRUCTURE"
    type:                              string

  - name:                              library
    displayName:                       "SAP Library configuration name, use the following syntax: ENV-LOCA-SAP_LIBRARY"
    type:                              string

  - name:                              environment
    displayName:                       "Environment name, MGMT, DEV, QA, etc"
    type:                              string
    default:                           MGMT

  - name:                              use_webapp_param
    displayName:                       "Deploy the configuration web application"
    type:                              boolean
    default:                           true

  - name:                              use_deployer
    displayName:                       Run on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string
    default:                           Control_Plane_Service_Connection

  - name:                              force_reset
    displayName:                       Force a re-install - may require multiple re-runs
    type:                              boolean
    default:                           false

  - name:                              test
    displayName:                       Perform a test deployment
    type:                              boolean
    default:                           false


variables:
  - group:                             "SDAF-General"

  - group:                             SDAF-${{ replace(parameters.deployer, '-INFRASTRUCTURE', '') }}

  - name:                              run_on
    value:                             $[replace(replace('True',eq(${{ parameters.use_deployer }}, 'True'), variables['POOL']),'True',variables['AGENT'])]

  - name:                              variable_group
    value:                             SDAF-${{ parameters.environment }}

  - name:                              variable_group_control_plane
    value:                             SDAF-${{ replace(parameters.deployer, '-INFRASTRUCTURE', '') }}

  - name:                              use_webapp
    value:                             ${{ lower(parameters.use_webapp_param) }}

  - name:                              deployer_foldername
    value:                             ${{ parameters.deployer }}

  - name:                              library_foldername
    value:                             ${{ parameters.library }}

  - name:                              log
    value:                             logfile_$(Build.BuildId)

  - name:                              tf_url
    value:                             https://releases.hashicorp.com/terraform/$(tf_version)/terraform_$(tf_version)_linux_amd64.zip

  - name:                              this_agent
    value:                             $[upper(coalesce(variables['POOL'], variables['AGENT']))]

  - name:                              connection_name
    value:                             ${{ parameters.connection_name }}

  - name:                              deployer_environment
    value:                             ${{ parameters.environment }}

  - name:                              force_reset
    value:                             ${{ parameters.force_reset }}

  - name:                              control_plane_name
    value:                             ${{ replace(parameters.deployer, '-INFRASTRUCTURE', '') }}
