---

- name:                               "Exports: Create SAP Directories"
  ansible.builtin.file:
    path:                             "{{ item.path }}"
    state:                            directory
    mode:                             0755
  loop:
    - { path: '{{ target_media_location }}' }
    - { path: '/usr/sap/trans' }
    - { path: '/sapmnt/{{ sap_sid | upper }}' }
  when:
    - node_tier == 'scs'
    - MULTI_SIDS is undefined
    - sap_mnt is undefined
    - sap_trans is undefined
    - usr_sap_install_mountpoint is undefined

- name:                               "Exports: Create SAP Directories for MSIDs"
  ansible.builtin.file:
    path:                             "{{ item.path }}"
    state:                            directory
    mode:                             0755
  loop:
    - { path: '/sapmnt' }
  when:
    - node_tier == 'scs'
    - MULTI_SIDS is defined

# Create Folders under sapmnt whilst using Local disk for Multi-SID installation.
- name:                                Create Filesystems under sapmnt
  block:
    - name:                            Create Filesystems for multi-sid installation
      ansible.builtin.file:
        path:                          /sapmnt/{{ item.sid }}
        state:                         directory
        mode:                          0755
      when:
        - node_tier == 'scs'
        - MULTI_SIDS is defined
      loop: "{{ MULTI_SIDS }}"

- name:                               "2.3 Exports: - Create SAP Directories (install)"
  block:

    - name:                           "2.3 Exports: - Create SAP Directories (install)"
      ansible.builtin.file:
        path:                         "{{ item.path }}"
        state:                        directory
        mode:                         0755
      loop:
        - { path: '{{ target_media_location }}' }

    - name:                           "2.3 Exports: - NFS Server Config on Suse (install)"
      ansible.builtin.lineinfile:
        path:                         "{{ item.path }}"
        regexp:                       "{{ item.regexp }}"
        line:                         "{{ item.line }}"
        owner:                        root
        group:                        root
        mode:                         0644
      loop:
        - { path: '/etc/exports',       regexp: '^{{ target_media_location }}',            line: '{{ target_media_location }} *(rw,sync,no_wdelay,no_root_squash)' }
          # - { tier: 'preparation', path: '/etc/sysconfig/nfs', regexp: '^NFS3_SERVER_SUPPORT=',        line: 'NFS3_SERVER_SUPPORT="no"' }
        - { path: '/etc/sysconfig/nfs', regexp: '^NFS3_SERVER_SUPPORT=',        line: 'NFS3_SERVER_SUPPORT="yes"'                            }
        - { path: '/etc/sysconfig/nfs', regexp: '^NFS4_SUPPORT=',               line: 'NFS4_SUPPORT="yes"'                                   }
      when:
        - (ansible_os_family | upper == "SUSE" or (ansible_os_family | lower ~ ansible_distribution_major_version) == "redhat7")

    - name:                            "2.3 Exports: - NFS Server Config on  : {{ ansible_os_family | lower ~ ansible_distribution_major_version }}"
      ansible.builtin.lineinfile:
        path:                          "{{ item.path }}"
        regexp:                        "{{ item.regexp }}"
        line:                          "{{ item.line }}"
        owner:                         root
        group:                         root
        mode:                          0644
      loop:
        - { path: '/etc/exports',   regexp: '^{{ target_media_location }}', line: '{{ target_media_location }} *(rw,sync,no_wdelay,no_root_squash)' }
        - { path: '/etc/nfs.conf',  regexp: '^# vers3=',                    line: ' vers3=y'                                                        }
        - { path: '/etc/nfs.conf',  regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
        - { path: '/etc/nfs.conf',  regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
      when:
        - distribution_id in ["redhat8", "redhat9"]

  when:
    - node_tier == 'scs'
    - usr_sap_install_mountpoint is undefined

- name:                                "2.3 Exports: - Create SAP Directories (sapmnt)"
  block:

    - name:                            "2.3 Exports: - Create SAP Directories (sapmnt)"
      ansible.builtin.file:
        path:                          "{{ item.path }}"
        state:                         directory
        mode:                          0755
      loop:
        - { path: '/sapmnt/{{ sap_sid | upper }}' }

    - name:                           "2.3 Exports: - NFS Server Config on Suse (sapmnt)"
      ansible.builtin.lineinfile:
        path:                         "{{ item.path }}"
        regexp:                       "{{ item.regexp }}"
        line:                         "{{ item.line }}"
        owner:                        root
        group:                        root
        mode:                         0644
      loop:
        - { path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid | upper }}', line: '/sapmnt/{{ sap_sid | upper }} *(rw,sync,no_wdelay,no_root_squash)' }
        - { path: '/etc/sysconfig/nfs', regexp: '^# RPCNFSDARGS=',              line: 'RPCNFSDARGS="-N 2 -N 3 -U"'                                      }
        - { path: '/etc/sysconfig/nfs', regexp: '^# RPCMOUNTDOPTS=',            line: 'RPCMOUNTDOPTS="-N 2 -N 3"'                                       }
      when:
        - (ansible_os_family | upper == "SUSE" or (ansible_os_family | lower ~ ansible_distribution_major_version) == "redhat7")

    - name:                            "2.3 Exports: - NFS Server Config on  : {{ ansible_os_family | lower ~ ansible_distribution_major_version }} (sapmnt)"
      ansible.builtin.lineinfile:
        path:   "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line:   "{{ item.line }}"
        owner:  root
        group:  root
        mode:   0644
      loop:
        - { path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid | upper }}', line: '/sapmnt/{{ sap_sid | upper }} *(rw,sync,no_wdelay,no_root_squash)' }
        - { path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=y'                                                        }
        - { path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
        - { path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
      when:
        - distribution_id == "redhat8"

  when:
    - node_tier == 'scs'
    - sap_mnt is undefined

- name:                                "2.3 Exports: - Create SAP Directories (saptrans)"
  block:

    - name:                           "2.3 Exports: - Exports: Create SAP Directories (saptrans)"
      ansible.builtin.file:
        path:                         "{{ item.path }}"
        state:                        directory
        mode:                         0755
      loop:
        - { path: '/usr/sap/trans' }

    - name:                            "Exports: NFS Server Config on  : {{ ansible_distribution | lower ~ ansible_distribution_major_version }}"
      ansible.builtin.lineinfile:
        path:                          "{{ item.path }}"
        regexp:                        "{{ item.regexp }}"
        line:                          "{{ item.line }}"
        owner:                         root
        group:                         root
        mode:                          0644
      loop:
        - { path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)' }
        - { path: '/etc/sysconfig/nfs', regexp: '^# RPCNFSDARGS=',              line: 'RPCNFSDARGS="-N 2 -N 3 -U"'                               }
        - { path: '/etc/sysconfig/nfs', regexp: '^# RPCMOUNTDOPTS=',            line: 'RPCMOUNTDOPTS="-N 2 -N 3"'                                }
      when:
        - (ansible_os_family | upper == "SUSE" or (ansible_os_family | lower ~ ansible_distribution_major_version) == "redhat7")

    - name:                            "Exports: NFS Server Config on  : {{ ansible_os_family | lower ~ ansible_distribution_major_version }}"
      ansible.builtin.lineinfile:
        path:                          "{{ item.path }}"
        regexp:                        "{{ item.regexp }}"
        line:                          "{{ item.line }}"
        owner:                         root
        group:                         root
        mode:                          0644
      loop:
        - { path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'       }
        - { path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=y'                                                        }
        - { path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
        - { path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
      when:
        - distribution_id == "redhat8"

  when:
    - node_tier == 'scs'
    - sap_trans is undefined

- name:                               "Exports: Create SAP Directories for MSIDs"
  ansible.builtin.file:
    path:                             "{{ item.path }}"
    state:                            directory
    mode:                             0755
  loop:
    - { path: '/sapmnt' }
  when:
    - node_tier == 'scs'
    - MULTI_SIDS is defined

# Create Folders under sapmnt whilst using Local disk for Multi-SID installation.
- name:                                Create Filesystems under sapmnt
  block:
    - name:                            Create Filesystems for multi-sid installation
      ansible.builtin.file:
        path:                          /sapmnt/{{ item.sid }}
        state:                         directory
        mode:                          0755
      when:
        - node_tier == 'scs'
        - MULTI_SIDS is defined
      loop: "{{ MULTI_SIDS }}"

- name:                                "Exports: NFS Server Config on Oracle Linux 8"
  ansible.builtin.lineinfile:
    path:                              "{{ item.path }}"
    regexp:                            "{{ item.regexp }}"
    line:                              "{{ item.line }}"
    owner:                             root
    group:                             root
    mode:                              0644
  loop:
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid | upper }}', line: '/sapmnt/{{ sap_sid | upper }} *(rw,sync,no_wdelay,no_root_squash)' }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'              }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^{{ target_media_location }}', line: '{{ target_media_location }} *(rw,sync,no_wdelay,no_root_squash)'            }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=n'                                                        }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
  when:
    - (ansible_distribution | lower ~ ansible_distribution_major_version) == "oraclelinux8"
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SIDS is not defined

- name:                                "Exports: NFS Server Config on Oracle Linux 8 for oracle Multi-SID installation"
  ansible.builtin.lineinfile:
    path:                              "{{ item.path }}"
    regexp:                            "{{ item.regexp }}"
    line:                              "{{ item.line }}"
    owner:                             root
    group:                             root
    mode:                              0644
  loop:
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'              }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^{{ target_media_location }}',            line: '{{ target_media_location }} *(rw,sync,no_wdelay,no_root_squash)'            }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=n'                                                        }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
  when:
    - (ansible_distribution | lower ~ ansible_distribution_major_version) == "oraclelinux8"
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SIDS is defined

- name:                                "Exports: NFS Server Config on Oracle Linux 8 for Multi-SID installation sapmnt mounts"
  ansible.builtin.lineinfile:
    path:                              "/etc/exports"
    regexp:                            "^/sapmnt/{{ item.sid | upper }}"
    line:                              "/sapmnt/{{ item.sid | upper }} *(rw,sync,no_wdelay,no_root_squash)"
    owner:                             root
    group:                             root
    mode:                              0644
  loop: "{{ MULTI_SIDS }}"
  when:
    - (ansible_distribution | lower ~ ansible_distribution_major_version) == "oraclelinux8"
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SIDS is defined

- name:                                "2.3 Exports: - Custom Exports"
  ansible.builtin.include_tasks:       "2.3-custom-exports.yaml"
  when:
    - custom_exports is defined

- name:                                "2.3 Exports: - Local NFS"
  block:
    - name:                            "2.3 Exports: - Set the NFS Service name {{ distribution_id }}"
      ansible.builtin.set_fact:
        nfs_service:                   'nfsserver'
      when:                            "'SUSE' == ansible_os_family | upper"

    - name:                            "2.3 Exports: - Set the NFS Service name {{ distribution_id }}"
      ansible.builtin.set_fact:
        nfs_service:                   "nfs-server"
      when:                            "'redhat8' == distribution_id or 'redhat9' == distribution_id"

    - name:                            "2.3 Exports: - Set the NFS Service name oracle {{ distribution_id }}"
      ansible.builtin.set_fact:
        nfs_service:                   "nfs-server"
      when:                            "'oraclelinux8' == distribution_id"

    - name:                            "2.3 Exports: - Set the NFS Service name {{ distribution_id }}"
      ansible.builtin.set_fact:
        nfs_service:                   'nfs'
      when:                            "'redhat7' == distribution_id"

    - name:                            "2.3 Exports: - NFS Ensure the NFS service is started"
      ansible.builtin.systemd:
        name:                          "{{ nfs_service }}"
        state:                         started
        enabled:                       true

    - name:                            "2.3 Exports: - NFS Ensure the NFS service is re-started"
      ansible.builtin.systemd:
        name:                          "{{ nfs_service }}"
        state:                         restarted

  when:
    - node_tier == 'scs'
    - (sap_trans is undefined) or (usr_sap_install_mountpoint is undefined) or (sap_mnt is undefined)
