---

# /*---------------------------------------------------------------------------8
# |  Variables in this file are required by the role,                          |
# |  but are computed from default variables (e.g. sid),                       |
# |  from the playbook/environment (e.g. hana_database),                       |
# |  or are "SAP standard" values.                                             |
# |                                                                            |
# |  They may be overridden, if required, but normally are not                 |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

hana_replication_mode:                 sync
hana_operation_mode:                   logreplay
hana_1_hsr_user:                       hdbhasync
hana_1_hsr_password:                   HSRpassw0rd

# For low spec Dev instances the timeout needs to be high
# A delay of 2 seconds is also recommended
# 2700 seconds is 45 minutes!
# May be overridden, if required
# hana_stop_start_timeout_in_seconds:    2700
# hana_stop_start_delay_in_seconds:      2
hana_stop_start_timeout_in_seconds:    600
hana_stop_start_delay_in_seconds:      10

# TODO: Maybe move these to a group_vars/all/distro file so that they
# can be shared by all playbooks/tasks automatically, and extend with
# standardised versions of all similar patterns used in the playbooks.
distro_name:    "{{ ansible_os_family | upper }}-{{ ansible_distribution_major_version }}"
distro_id:      "{{ ansible_os_family | lower ~ ansible_distribution_major_version }}"
