# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

scs_virtual_hostname:                  "{{ sap_sid | lower }}scs{{ scs_instance_number }}cl1"
ers_virtual_hostname:                  "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"
iscsi_object:                          iqn.2006-04

iscsi_port:                            3260

sapcontrol_command:                    "sapcontrol -nr {{ scs_instance_number }}"

cluster_cleanup_cmd:
  RedHat: "pcs resource cleanup"
  Suse: "crm resource cleanup"
