# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

is_UEK6:                           "{{ ansible_kernel is version('5.5', '<') }}"
CV_ASSUME_DISTID:                  "{% if ansible_kernel is version('5.5', '<') %} OEL7 {% else %} OEL{{ ansible_distribution_version }} {% endif %}"
