# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                         OS Base Disk Configuration                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Task: 1.5     - os-disk-setup
#
# -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
#
# <Comment Header>
#
# -------------------------------------+---------------------------------------8

# ----------------------------------------
# BEGIN
# ----------------------------------------

# ----------------------------------------
# END
# ----------------------------------------

# -------------------------------------+---------------------------------------8
#

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Load the disk configuration settings"
  ansible.builtin.include_vars:        disks_config_asm.yml


- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Check if the shared disk exists"
  ansible.builtin.set_fact:
    shareddisk:                        "{{ disks | selectattr('host', 'defined') |
      selectattr('host', 'equalto', inventory_hostname) |
      selectattr('type', 'equalto', 'shared') |
      map(attribute='type') | sort | unique |
      list | length }}"

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Append 'sapmnt' if needed"
  ansible.builtin.set_fact:
    logical_volumes:                   "{{ logical_volumes + logical_volumes_sapmnt }}"
  when: sap_mnt is not defined

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Append 'install' if needed"
  ansible.builtin.set_fact:
    logical_volumes:                   "{{ logical_volumes + logical_volumes_install }}"
  when: usr_sap_install_mountpoint is not defined

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Show disk info"
  ansible.builtin.debug:
    msg:
      - "Unique disks:    {{ disktypes }} "
      - "Volume groups:   {{ volume_groups }} "
      - "Logical volumes: {{ logical_volumes }} "
    verbosity:                         2

# CREATE VOLUME GROUPS BASED ON sap-parameters.yaml
# -------------------------------------+---------------------------------------8
#
- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Volume Group creation"
  community.general.lvg:
    vg:                                "{{ item.vg }}"
    pvs:                               "{{ item.pvs }}"
    pesize:                            4M
    state:                             present
  loop:                                "{{ volume_groups }}"
  register:                            volume_groups_created
  when:
    - tier == "sapos"
    - node_tier == "oracle-asm"

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Print vgcreated details"
  ansible.builtin.debug:
    msg:                               "VOLUME GROUPS: {{ volume_groups_created | json_query('results[*].item') }}"
    verbosity:                         2
  when:
    - tier == "sapos"
    - volume_groups_created is defined

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Filter the volume group names from volume_groups_created results"
  ansible.builtin.set_fact:
    volume_group_list:                 "{{ volume_groups_created | json_query('results[*].item.vg') }}"
  when:
    - tier == "sapos"


# CREATE LOGICAL VOLUMES BASED ON volume_group_list
# -------------------------------------+---------------------------------------8
#
- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Logical Volume creation"
  community.general.lvol:
    lv:                                "{{ item.lv }}"
    vg:                                "{{ item.vg }}"
    size:                              "{{ item.size }}"
    opts:                              "{{ lvol_opts_from_lv_item }}"
    active:                            true
    state:                             present
    shrink:                            false
    resizefs:                          false
  loop:                                "{{ logical_volumes }}"
  register:                            logical_volumes_created
  when:
    - tier == "sapos"
    - item.node_tier | intersect([ 'all', supported_tiers ] | flatten(levels=1)) or
      item.node_tier in [ 'all', supported_tiers ] | flatten(levels=1)
    - item.vg in volume_group_list

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Filter the logical volumes created results"
  ansible.builtin.set_fact:
    logical_volume_list_tmp:           "{{ logical_volumes_created.results | rejectattr('skipped', 'defined') | list }}"
  when:
    - tier == "sapos"

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Get the logical volumes from the list"
  ansible.builtin.set_fact:
    logical_volume_list:               "{{ logical_volume_list_tmp | map(attribute='item.lv') | list }}"
  when:
    - tier == "sapos"

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Filesystem creation"
  community.general.filesystem:
    dev:                               "{{ dev_path_from_lv_item }}"
    fstype:                            "{{ item.fstype }}"
    opts:                              "{{ item.fsopts | default('') }}"
  loop:                                "{{ logical_volumes }}"
  register :                           filesystems_created
  when:
    - item.tier in ["all", tier ]
    - item.node_tier | intersect([ 'all', supported_tiers ] | flatten(levels=1)) or
      item.node_tier in [ 'all', supported_tiers ] | flatten(levels=1)
    - item.fstype is defined
    - item.lv in logical_volume_list

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Filter the filesystem created results"
  ansible.builtin.set_fact:
    filesystems_created_list:          "{{ filesystems_created.results | rejectattr('skipped', 'defined') | list }}"
  when:
    - tier == "sapos"

- name:                                "1.5.1.1 Disk Setup - ORACLE ASM - Debug disk information"
  ansible.builtin.debug:
    msg:
      - "Created Volume Groups:    {{ volume_group_list }} "
      - "Created Logical Volumes:  {{ logical_volume_list }} "
      - "Created Filesystems:      {{ filesystems_created_list }} "
    verbosity:                         2
  when:
    - tier == "sapos"

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
