---
name:               'HANA_2_00_061_v0001ms'
target:             'HANA 2.0'
version:            1
platform:           'HANA'
materials:

  media:
    # SAPCAR 7.22
    - name:         "SAPCAR 7.22; OS: Linux on x86_64 64bit"
      archive:      SAPCAR_1115-70006178.EXE
      checksum:     765412436934362cc5497e3d659fbb78be91093a091c11ec4fbe84dfb415a0e5
      filename:     SAPCAR
      permissions:  '0755'
      url:          https://softwaredownloads.sap.com/file/0020000000098642022

    # HANA Client v2.12
    - name:         "SAP HANA CLIENT Version 2.12"
      archive:      IMDB_CLIENT20_012_25-80002082.SAR
      checksum:     13209e0326680d345f8e57513b63b4e52581a5ddfffe45eff9f5e4f3283d6684
      extract:      true
      extractDir:   CD_HDBCLIENT
      creates:      SIGNATURE.SMF
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000000626062022

    # v2_00_061 Revision 2.00.061.0 (SPS06) for HANA DB 2.0
    - name:         HANA Server
      archive:      IMDB_SERVER20_061_0-80002031.SAR
      checksum:     c30944dc57d932f5f2b5f1feb409937d9dbb773d196c67e06142736976b79317
      extract:      true
      extractDir:   CD_HDBSERVER
      creates:      SIGNATURE.SMF
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000000198352022

    - name:         SAP HANA AFL Rev 61.2 only for HANA 2.0 Rev 61
      archive:      IMDB_AFL20_061_2-80001894.SAR
      checksum:     fac33ee4cdad5b956d1e029496318d2fc2ba93dee8cbaa4ac01c68cbbc5d222b
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_AFL/packages
      url:          https://softwaredownloads.sap.com/file/0020000000340382022

    - name:         LCAPPS for HANA 2.00.061.00 Build 101.04 PL 000
      archive:      IMDB_LCAPPS_2061_0-20010426.SAR
      checksum:     d3fd0aa9424189b5a8145f8a9286e6bf47209f05cfd97c2d4fc78eb2d4d11cb3
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/SAP_HANA_LCAPPS/packages
      url:          https://softwaredownloads.sap.com/file/0020000000197922022

    - name:         VCH AFL 2021 Rev 61 only for HANA 2.0 Rev 61
      archive:      VCH202100_2061_0-70006349.SAR
      checksum:     b385f1c85c2cdccd2aefc21471152b56237b23a7ba7f6c7727b8c7d78c6d239f
      extract:      true
      extractDir:   CD_HDBSERVER/COMPONENTS
      creates:      COMPONENTS/VCH_AFL_2021/packages
      url:          https://softwaredownloads.sap.com/file/0020000000198312022

    - name:         "SAP HOST AGENT 7.22 SP55"
      archive:      SAPHOSTAGENT55_55-80004822.SAR
      checksum:     9a93391c1a52dff5368e834dc0d16c84e69f99ef39d3b6bdfc58b99af6d85553
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000000239812022


    - name:         SAPHostAgent RPM Package
      archive:      saphostagentrpm_55-80004822.rpm
      checksum:     0de3615a063ec6a292d680172ce6d09388d969e4978b1f6572223787b03c0f37
      url:          https://softwaredownloads.sap.com/file/0020000000208912022

...
