
name: Ansible Lint
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout the code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 #v6.1.0
        with:
          python-version: '3.10'

      - name: Install Ansible and Ansible-Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.16.* ansible-lint==24.9.2 jmespath netaddr

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install ansible.windows --force
          ansible-galaxy collection install ansible.posix --force
          ansible-galaxy collection install ansible.utils --force
          ansible-galaxy collection install ansible.netcommon:5.1.2 --force
          ansible-galaxy collection install community.windows --force
          ansible-galaxy collection install community.general --force
          ansible-galaxy collection install microsoft.ad --force

      - name: Run ansible-lint
        run: |
          ansible-lint deploy/ansible -c .ansible-lint
