
name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible-Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint==24.2.0 jmespath netaddr

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install ansible.windows --force
          ansible-galaxy collection install ansible.posix --force
          ansible-galaxy collection install ansible.utils --force
          ansible-galaxy collection install ansible.netcommon:5.1.2 --force
          ansible-galaxy collection install community.windows --force
          ansible-galaxy collection install community.general --force
          ansible-galaxy collection install microsoft.ad --force

      - name: Run ansible-lint
        run: |
          ansible-lint deploy/ansible -c .ansible-lint
