---

# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM Template File
# <BOM>-scs-inifile-param.j2
#
# -------------------------------------+---------------------------------------8

# ------------------<DEBUGGING>-------------------
- name:                                Parameters
  ansible.builtin.debug:
    msg:
      - "SAP SID              :        {{ sap_sid }}"
      - "Instance Number - SCS:        {{ scs_instance_number | default('') }}"
      - "SCS Virtual Hostname :        {{ sap_scs_hostname | default('') }}"
      - "DB Hostname          :        {{ sap_db_hostname | default('') }}"
      - "FQDN                 :        {{ sap_fqdn }}"
      - "sapadm UID           :        {{ sapadm_uid }}"
      - "sapsys GID           :        {{ sapsys_gid }}"
      - "<sid>adm UID         :        {{ sidadm_uid }}"
    verbosity:                         2
# ------------------</DEBUGGING>------------------


# -------------------------------------+---------------------------------------8
#
# Look for template in the storage account first
#
# -------------------------------------+---------------------------------------8

- name:                                "3.3.1 BoM Template Processing: - Set the new name"
  ansible.builtin.set_fact:
    new_bom_name:                      "{{ bom_base_name }}{{ bom_suffix }}"

#   0x) Create hidden directory for parameter files
- name:                                "3.3.1 BoM Template processing: Create hidden directory"
  ansible.builtin.file:
    path:                              "{{ param_directory }}"
    state:                             directory
    mode:                              '0755'

#   Ensure the download directory exists on the agent
- name:                                "3.3.1 BoM Template processing: Ensure download directory exists"
  ansible.builtin.file:
    path:                              "{{ download_directory }}/bom"
    state:                             directory
    mode:                              '0755'

- name:                                "3.3.1 BoM Template processing: {{ bom_name }} Download: {{ sap_inifile_template }} from the storage account"
  ansible.builtin.get_url:
    url:                               "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_name }}/templates/\
                                        {{ sap_inifile_template }}{% if sapbits_sas_token is not undefined %}?{{ sapbits_sas_token }}{% endif %}"
    dest:                              "{{ download_directory }}/bom/{{ sap_inifile_template }}"
    mode:                              0644
    force:                             true
  delegate_to:                         localhost
  become:                              "{{ bom_processing_become }}"
  register:                            result
  when:
    - not always_upload_jinja_templates

- name:                                "3.3.1 BoM Template processing: Remove ini file {{ sap_inifile }}"
  ansible.builtin.file:
    path:                              "{{ param_directory }}/{{ sap_inifile }}"
    state:                             absent

- name:                                "3.3.1 BoM Template processing: Create ini files ({{ bom_base_name }})"
  block:

    - name:                            "3.3.1 BoM Template processing: Create ini file {{ sap_inifile }} from {{ sap_inifile_template }}"
      ansible.builtin.template:
        src:                           "{{ download_directory }}/bom/{{ sap_inifile_template }}"
        dest:                          "{{ param_directory }}/{{ sap_inifile }}"
        # remote_src:                    yes
        mode:                          0644
        force:                         true

  when:
    - result is succeeded or result is skipped

- name:                                "ErrorHandling"
  ansible.builtin.fail:
    msg:                               "TEMPLATE:0001:Unable to find {{ sap_inifile_template }} in the storage account"
  when: result is failed

# -------------------------------------+---------------------------------------8
#
# Look for template on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

- name:                                "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template on disk"
  block:
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template"
      ansible.builtin.stat:
        path:                          "{{ BOM_directory }}/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
      register:                        microsoft_supplied_bom_template
      delegate_to:                     localhost
      become:                          "{{ bom_processing_become }}"

    - name:                            "{{ task_prefix }} Create ini file {{ sap_inifile }}"
      ansible.builtin.template:
        src:                           "{{ microsoft_supplied_bom_template.stat.path }}"
        dest:                          "{{ param_directory }}/{{ sap_inifile }}"
        mode:                          0644
        force:                         true
      when:                            microsoft_supplied_bom_template.stat.exists

# -------------------------------------+---------------------------------------8
#
# Look for template in archives on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template from archive on disk"
      block:

        - name:                        "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) ini file in archive"
          ansible.builtin.stat:
            path:                      "{{ BOM_directory }}/archives/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
          register:                    microsoft_supplied_bom_template_archive
          delegate_to:                 localhost
          become:                      "{{ bom_processing_become }}"

        - name:                        "{{ task_prefix }} Create ini file {{ sap_inifile }}"
          ansible.builtin.template:
            src:                       "{{ microsoft_supplied_bom_template.stat.path }}"
            dest:                      "{{ param_directory }}/{{ sap_inifile }}"
            mode:                      0644
            force:                     true
          when:                        microsoft_supplied_bom_template_archive.stat.exists
      when:                            not microsoft_supplied_bom_template.stat.exists

  when:                                result is failed or always_upload_jinja_templates

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
