---

# -------------------------------------+---------------------------------------8
#
# Description:  Download specified BOM Template File
# <BOM>-scs-inifile-param.j2
#
# -------------------------------------+---------------------------------------8

# ------------------<DEBUGGING>-------------------
- name:                                Parameters
  ansible.builtin.debug:
    msg:
      - "SAP SID              :        {{ sap_sid }}"
      - "Instance Number - SCS:        {{ scs_instance_number }}"
      - "SCS Virtual Hostname :        {{ sap_scs_hostname }}"
      - "DB Hostname          :        {{ sap_db_hostname }}"
      - "FQDN                 :        {{ sap_fqdn }}"
      - "sapadm UID           :        {{ sapadm_uid }}"
      - "sapsys GID           :        {{ sapsys_gid }}"
      - "<sid>adm UID         :        {{ sidadm_uid }}"
    verbosity:                         2
# ------------------</DEBUGGING>------------------

# -------------------------------------+---------------------------------------8
#
# Look for template in the storage account first
#
# -------------------------------------+---------------------------------------8

- name:                                "3.3 BoM Processing: - Set Python version {{ distribution_id }}"
  ansible.builtin.set_fact:
    python_version:                    'python2'

- name:                                "3.3 BoM Processing: - Set Python version {{ distribution_id }}"
  ansible.builtin.set_fact:
    python_version:                    'python3'
  when:                                distribution_id in ['suse15', 'redhat8']

- name:                                "{{ task_prefix }} Download BOM ({{ bom_base_name }}) template from Storage Account"
  ansible.builtin.get_url:
    url:                               "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/\
                                        {{ sap_inifile_template }}{{ sapbits_sas_token }}"
    dest:                              "{{ download_directory }}/bom/{{ sap_inifile_template }}"
    mode:                              0644
  register:                            result
  vars:
    ansible_python_interpreter:        "{{ python_version }}"
  when:                                distribution_id in ['suse15', 'redhat8']

- name:                                "BOM2: {{ bom_name }} Check is file {{ bom_name }} is already downloaded to the storage account"
  ansible.builtin.get_url:
    url:                               "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ bom_base_name }}/templates/\
                                        {{ sap_inifile_template }}{{ sapbits_sas_token }}"
    dest:                              "{{ download_directory }}/bom/{{ sap_inifile_template }}"
    mode:                              0644
  register:                            result
  when:
    - distribution_id != 'suse15'
    - distribution_id != 'redhat8'

- name:                                "BOM: Download BOM ({{ bom_name }}) from Storage Account"
  block:

    - name:                            "{{ task_prefix }} Create ini file {{ sap_inifile }}"
      ansible.builtin.template:
        src:                           "{{ download_directory }}/bom/{{ sap_inifile_template }}"
        dest:                          /usr/sap/install/downloads/{{ sap_inifile }}
        mode:                          0644
        force:                         true
      
  when:                                
    - result is succeeded or result is skipped

# -------------------------------------+---------------------------------------8
#
# Look for template on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

- name:                                "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template on disk" 
  block:
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template"
      ansible.builtin.stat:
        path:                          "{{ playbook_dir }}/BOM-catalog/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
      register:                        microsoft_supplied_bom_template
      delegate_to:                     localhost

    - name:                            "{{ task_prefix }} Create ini file {{ sap_inifile }}"
      ansible.builtin.template:
        src:                           "{{ microsoft_supplied_bom_template.stat.path }}"
        dest:                          /usr/sap/install/downloads/{{ sap_inifile }}
        mode:                          0644
        force:                         true
      when:                            microsoft_supplied_bom_template.stat.exists

# -------------------------------------+---------------------------------------8
#
# Look for template in archives on disk if not found in storage account
#
# -------------------------------------+---------------------------------------8

    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) template from archive on disk" 
      block:

        - name:                        "{{ task_prefix }} Check for Microsoft Supplied BOM ({{ bom_base_name }}) ini file in archive"
          ansible.builtin.stat:
            path:                      "{{ playbook_dir }}/BOM-catalog/archives/{{ bom_base_name }}/templates/{{ sap_inifile_template }}"
            register:                  microsoft_supplied_bom_template_archive
            delegate_to:               localhost

        - name:                        "{{ task_prefix }} Create ini file {{ sap_inifile }}"
          ansible.builtin.template:
            src:                       "{{ microsoft_supplied_bom_template.stat.path }}"
            dest:                      /usr/sap/install/downloads/{{ sap_inifile }}
            mode:                      0644
            force:                     true
          when:                        microsoft_supplied_bom_template_archive.stat.exists
      when:                            not microsoft_supplied_bom_template.stat.exists

  when:                                result is failed


# -------------------------------------+---------------------------------------8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
